-- Platform foundation: helper functions, customer instance configuration,
-- organization / property structure and identity & access.
-- Conventions (Technical Doc §7.2): UUIDv7 ids generated by the application,
-- timestamptz, snake_case plural tables, status as text + CHECK.

-- +goose Up
CREATE SCHEMA IF NOT EXISTS platform;
CREATE EXTENSION IF NOT EXISTS btree_gist;
CREATE EXTENSION IF NOT EXISTS citext;

-- +goose StatementBegin
-- Row Level Security predicate (FR-TEC-04, Technical Doc §7.1). The API sets
-- app.property_ids / app.all_properties with SET LOCAL in every transaction
-- (kernel/dbtx). Missing settings deny access.
CREATE FUNCTION platform.rls_allowed(pid uuid) RETURNS boolean
LANGUAGE sql STABLE PARALLEL SAFE AS $$
  SELECT coalesce(current_setting('app.all_properties', true), '') = 'on'
      OR (pid IS NOT NULL AND pid = ANY (coalesce(nullif(current_setting('app.property_ids', true), ''), '{}')::uuid[]))
$$;

CREATE FUNCTION platform.touch_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END $$;

-- Grants the per-instance application role (stored by provisioning in the
-- database-level setting oneclub.app_role) access to a schema.
-- append_only = true grants only SELECT/INSERT (audit schema, FR-AUD-03).
CREATE FUNCTION platform.grant_app(target_schema text, append_only boolean DEFAULT false) RETURNS void
LANGUAGE plpgsql AS $$
DECLARE
  app_role text := current_setting('oneclub.app_role', true);
  rep_role text := current_setting('oneclub.report_role', true);
BEGIN
  IF app_role IS NOT NULL AND app_role <> '' THEN
    EXECUTE format('GRANT USAGE ON SCHEMA %I TO %I', target_schema, app_role);
    IF append_only THEN
      EXECUTE format('GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA %I TO %I', target_schema, app_role);
      EXECUTE format('REVOKE UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA %I FROM %I', target_schema, app_role);
    ELSE
      EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA %I TO %I', target_schema, app_role);
    END IF;
    EXECUTE format('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA %I TO %I', target_schema, app_role);
    EXECUTE format('GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA %I TO %I', target_schema, app_role);
  ELSE
    RAISE NOTICE 'oneclub.app_role not set; skipping grants for schema %', target_schema;
  END IF;
  IF rep_role IS NOT NULL AND rep_role <> '' THEN
    EXECUTE format('GRANT USAGE ON SCHEMA %I TO %I', target_schema, rep_role);
    EXECUTE format('GRANT SELECT ON ALL TABLES IN SCHEMA %I TO %I', target_schema, rep_role);
    EXECUTE format('GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA %I TO %I', target_schema, rep_role);
  END IF;
END $$;

-- Adds property RLS to a table with a property_id column.
CREATE FUNCTION platform.enable_property_rls(tbl regclass, col text DEFAULT 'property_id') RETURNS void
LANGUAGE plpgsql AS $$
BEGIN
  EXECUTE format('ALTER TABLE %s ENABLE ROW LEVEL SECURITY', tbl);
  EXECUTE format('CREATE POLICY property_isolation ON %s USING (platform.rls_allowed(%I)) WITH CHECK (platform.rls_allowed(%I))', tbl, col, col);
END $$;

-- Standard updated_at trigger.
CREATE FUNCTION platform.add_touch_trigger(tbl regclass) RETURNS void
LANGUAGE plpgsql AS $$
BEGIN
  EXECUTE format('CREATE TRIGGER touch_updated_at BEFORE UPDATE ON %s FOR EACH ROW EXECUTE FUNCTION platform.touch_updated_at()', tbl);
END $$;
-- +goose StatementEnd

-- ── EP-01 Customer Instance ────────────────────────────────────────────────
-- One row per database: the database IS the customer instance (FR-INS-02).
CREATE TABLE platform.instance (
  singleton        boolean PRIMARY KEY DEFAULT true CHECK (singleton),
  id               uuid NOT NULL,
  code             text NOT NULL CHECK (code ~ '^[a-z][a-z0-9-]{1,30}$'),
  name             text NOT NULL,
  default_locale   text NOT NULL DEFAULT 'id' CHECK (default_locale IN ('en', 'id')),
  currency         char(3) NOT NULL DEFAULT 'IDR',
  timezone         text NOT NULL DEFAULT 'Asia/Jakarta',
  status           text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'suspended')),
  default_theme    text NOT NULL DEFAULT 'light' CHECK (default_theme IN ('light', 'dark')),
  branding         jsonb NOT NULL DEFAULT '{}'::jsonb,   -- FR-INS-07 / FR-BRD-01
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  updated_by       uuid
);

-- FR-INS-04 Enabled Modules
CREATE TABLE platform.modules (
  code        text PRIMARY KEY,
  name        text NOT NULL,
  layer       text NOT NULL,
  sort_order  int NOT NULL DEFAULT 0,
  enabled     boolean NOT NULL DEFAULT false,
  always_on   boolean NOT NULL DEFAULT false,
  updated_at  timestamptz NOT NULL DEFAULT now(),
  updated_by  uuid
);

-- FR-INS-05 Feature Flags / Feature Configuration
CREATE TABLE platform.feature_flags (
  key          text PRIMARY KEY CHECK (key ~ '^[a-z][a-z0-9_.]{1,80}$'),
  description  text NOT NULL DEFAULT '',
  value        jsonb NOT NULL DEFAULT 'false'::jsonb,
  value_type   text NOT NULL DEFAULT 'boolean' CHECK (value_type IN ('boolean', 'string', 'number', 'json')),
  client_visible boolean NOT NULL DEFAULT true,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),
  updated_by   uuid
);

-- FR-INS-06 Custom Domain per application surface
CREATE TABLE platform.domains (
  id                  uuid PRIMARY KEY,
  surface             text NOT NULL CHECK (surface IN ('web', 'member', 'backoffice', 'ops', 'platform-admin', 'api')),
  hostname            citext NOT NULL UNIQUE,
  status              text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'verified', 'active', 'failed')),
  verification_token  text NOT NULL,
  verified_at         timestamptz,
  last_checked_at     timestamptz,
  last_error          text,
  created_at          timestamptz NOT NULL DEFAULT now(),
  created_by          uuid,
  updated_at          timestamptz NOT NULL DEFAULT now(),
  updated_by          uuid
);

-- ── EP-02 Organization & Property ──────────────────────────────────────────
CREATE TABLE platform.organization (
  singleton     boolean PRIMARY KEY DEFAULT true CHECK (singleton),
  id            uuid NOT NULL,
  legal_name    text NOT NULL,
  display_name  text NOT NULL,
  npwp          text,
  address       text,
  city          text,
  province      text,
  postal_code   text,
  phone         text,
  email         text,
  website       text,
  logo_file_id  uuid,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  updated_by    uuid
);

CREATE TABLE platform.properties (
  id           uuid PRIMARY KEY,
  code         text NOT NULL UNIQUE CHECK (code ~ '^[A-Z0-9][A-Z0-9_-]{0,19}$'),
  name         text NOT NULL,
  address      text,
  city         text,
  phone        text,
  email        text,
  timezone     text,              -- NULL = instance timezone (FR-L10N-02)
  status       text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  created_at   timestamptz NOT NULL DEFAULT now(),
  created_by   uuid,
  updated_at   timestamptz NOT NULL DEFAULT now(),
  updated_by   uuid,
  archived_at  timestamptz
);
SELECT platform.enable_property_rls('platform.properties', 'id');
SELECT platform.add_touch_trigger('platform.properties');

-- ── EP-03 Identity & Access ────────────────────────────────────────────────
CREATE TABLE platform.users (
  id                   uuid PRIMARY KEY,
  email                citext NOT NULL UNIQUE,
  full_name            text NOT NULL,
  phone                text,
  employee_id          uuid,                 -- FK added with employees
  status               text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  password_hash        text,
  password_changed_at  timestamptz,
  must_change_password boolean NOT NULL DEFAULT false,
  mfa_enabled          boolean NOT NULL DEFAULT false,
  mfa_secret_enc       bytea,
  mfa_pending_secret_enc bytea,
  failed_login_count   int NOT NULL DEFAULT 0,
  locked_until         timestamptz,
  last_login_at        timestamptz,
  locale               text CHECK (locale IN ('en', 'id')),
  theme                text CHECK (theme IN ('light', 'dark', 'system')),
  pin_hash             text,
  created_at           timestamptz NOT NULL DEFAULT now(),
  created_by           uuid,
  updated_at           timestamptz NOT NULL DEFAULT now(),
  updated_by           uuid
);
SELECT platform.add_touch_trigger('platform.users');

-- Permission catalogue, synchronised from code at every migrate/startup.
CREATE TABLE platform.permissions (
  code         text PRIMARY KEY CHECK (code ~ '^[a-z_]+\.[a-z_]+\.[a-z_]+$'),
  module       text NOT NULL,
  object       text NOT NULL,
  action       text NOT NULL,
  description  text NOT NULL DEFAULT '',
  platform_only boolean NOT NULL DEFAULT false
);

CREATE TABLE platform.roles (
  id            uuid PRIMARY KEY,
  code          text NOT NULL UNIQUE CHECK (code ~ '^[a-z][a-z0-9_]{1,60}$'),
  name          text NOT NULL,
  description   text NOT NULL DEFAULT '',
  category      text NOT NULL,
  scope         text NOT NULL CHECK (scope IN ('platform', 'instance', 'property')),
  is_template   boolean NOT NULL DEFAULT false,   -- seeded from Product Overview §44
  mfa_required  boolean NOT NULL DEFAULT false,   -- FR-IAM-03
  status        text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  created_at    timestamptz NOT NULL DEFAULT now(),
  created_by    uuid,
  updated_at    timestamptz NOT NULL DEFAULT now(),
  updated_by    uuid
);
SELECT platform.add_touch_trigger('platform.roles');

CREATE TABLE platform.role_permissions (
  role_id          uuid NOT NULL REFERENCES platform.roles (id) ON DELETE CASCADE,
  permission_code  text NOT NULL REFERENCES platform.permissions (code) ON DELETE CASCADE,
  PRIMARY KEY (role_id, permission_code)
);

-- FR-IAM-07: a user can hold different roles at different properties.
-- property_id NULL = instance-wide (Platform Admin / Super Admin).
CREATE TABLE platform.role_assignments (
  id           uuid PRIMARY KEY,
  user_id      uuid NOT NULL REFERENCES platform.users (id) ON DELETE CASCADE,
  role_id      uuid NOT NULL REFERENCES platform.roles (id),
  property_id  uuid REFERENCES platform.properties (id),
  created_at   timestamptz NOT NULL DEFAULT now(),
  created_by   uuid
);
CREATE UNIQUE INDEX role_assignments_uniq ON platform.role_assignments
  (user_id, role_id, coalesce(property_id, '00000000-0000-0000-0000-000000000000'::uuid));
CREATE INDEX role_assignments_property ON platform.role_assignments (property_id);

CREATE TABLE platform.devices (
  id               uuid PRIMARY KEY,
  property_id      uuid NOT NULL REFERENCES platform.properties (id),
  name             text NOT NULL,
  device_type      text NOT NULL CHECK (device_type IN ('pos', 'tablet', 'kiosk', 'other')),
  outlet_id        uuid,
  token_hash       text UNIQUE,
  status           text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  last_seen_at     timestamptz,
  created_at       timestamptz NOT NULL DEFAULT now(),
  created_by       uuid,
  updated_at       timestamptz NOT NULL DEFAULT now(),
  updated_by       uuid
);
SELECT platform.enable_property_rls('platform.devices');
SELECT platform.add_touch_trigger('platform.devices');

-- Opaque, revocable sessions (FR-IAM-02, FR-IAM-10).
CREATE TABLE platform.sessions (
  id              uuid PRIMARY KEY,
  user_id         uuid NOT NULL REFERENCES platform.users (id) ON DELETE CASCADE,
  token_hash      text NOT NULL UNIQUE,
  kind            text NOT NULL DEFAULT 'web' CHECK (kind IN ('web', 'device')),
  device_id       uuid REFERENCES platform.devices (id),
  property_id     uuid REFERENCES platform.properties (id), -- device shift property
  mfa_verified    boolean NOT NULL DEFAULT false,
  ip              text,
  user_agent      text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  last_seen_at    timestamptz NOT NULL DEFAULT now(),
  expires_at      timestamptz NOT NULL,
  revoked_at      timestamptz,
  revoked_reason  text
);
CREATE INDEX sessions_user ON platform.sessions (user_id) WHERE revoked_at IS NULL;

CREATE TABLE platform.password_reset_tokens (
  id          uuid PRIMARY KEY,
  user_id     uuid NOT NULL REFERENCES platform.users (id) ON DELETE CASCADE,
  token_hash  text NOT NULL UNIQUE,
  expires_at  timestamptz NOT NULL,
  used_at     timestamptz,
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- FR-INT-06 server-to-server API keys.
CREATE TABLE platform.api_keys (
  id            uuid PRIMARY KEY,
  name          text NOT NULL,
  prefix        text NOT NULL UNIQUE,
  secret_hash   text NOT NULL,
  scopes        text[] NOT NULL DEFAULT '{}',
  property_id   uuid REFERENCES platform.properties (id),
  expires_at    timestamptz,
  revoked_at    timestamptz,
  last_used_at  timestamptz,
  rotated_at    timestamptz,
  created_at    timestamptz NOT NULL DEFAULT now(),
  created_by    uuid,
  updated_at    timestamptz NOT NULL DEFAULT now(),
  updated_by    uuid
);

SELECT platform.grant_app('platform');

-- +goose Down
DROP SCHEMA platform CASCADE;
