// Obfuscates the built JavaScript of a VPS release in place (Technical Doc
// §9.4): the Staff App and Member App bundles, the website's client chunks
// and its server code. Run only by the VPS image build (Dockerfile.web with
// OBFUSCATE=true); development, CI and Dev keep readable builds.
//
//   node scripts/obfuscate.mjs <browser|node> <dir>...
//
// The settings rename identifiers and move strings into a rotated string
// array. Control-flow flattening, dead code and self-defending stay off: they
// cost tablets and the offline POS too much speed and break on reformatting.
// Imports keep their literal paths so chunk loading and preloads still work.
// The website's browser chunks are classic scripts sharing one global scope,
// so the helpers each file gets (string array, decoder) carry a prefix unique
// to that file; otherwise a later chunk would replace an earlier one's decoder.

import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import JavaScriptObfuscator from 'javascript-obfuscator';

const [target, ...dirs] = process.argv.slice(2);
if (!['browser', 'node'].includes(target) || dirs.length === 0) {
  console.error('usage: node scripts/obfuscate.mjs <browser|node> <dir>...');
  process.exit(2);
}

/** Service workers generated by Workbox: not our code, and their precache list must stay as built. */
const SKIP = /(^|[\\/])(sw|workbox-[^\\/]*)\.js$/;

const options = {
  target,
  compact: true,
  simplify: true,
  identifierNamesGenerator: 'mangled-shuffled',
  renameGlobals: false,
  renameProperties: false,
  transformObjectKeys: false,
  ignoreImports: true,
  stringArray: true,
  stringArrayThreshold: 0.75,
  stringArrayRotate: true,
  stringArrayShuffle: true,
  stringArrayIndexShift: true,
  stringArrayWrappersCount: 1,
  stringArrayWrappersType: 'variable',
  stringArrayEncoding: [],
  splitStrings: false,
  controlFlowFlattening: false,
  deadCodeInjection: false,
  numbersToExpressions: false,
  selfDefending: false,
  debugProtection: false,
  disableConsoleOutput: false,
  unicodeEscapeSequence: false,
  sourceMap: false,
  advertisement: false,
  seed: process.env.OBFUSCATE_SEED || 0,
};

function* files(dir) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) yield* files(p);
    else if (p.endsWith('.js') && !SKIP.test(p)) yield p;
  }
}

let count = 0;
let before = 0;
let after = 0;
const started = Date.now();
for (const dir of dirs) {
  for (const file of files(dir)) {
    const code = readFileSync(file, 'utf8');
    let out;
    try {
      const prefix = `_${createHash('sha1').update(relative(process.cwd(), file)).digest('hex').slice(0, 6)}`;
      out = JavaScriptObfuscator.obfuscate(code, { ...options, identifiersPrefix: prefix, inputFileName: file }).getObfuscatedCode();
    } catch (e) {
      console.error(`obfuscate: ${relative(process.cwd(), file)}: ${e instanceof Error ? e.message : String(e)}`);
      process.exit(1);
    }
    writeFileSync(file, out);
    count++;
    before += code.length;
    after += out.length;
  }
}
const mb = (n) => (n / 1048576).toFixed(1);
console.log(`obfuscated ${count} ${target} files: ${mb(before)} MB → ${mb(after)} MB in ${((Date.now() - started) / 1000).toFixed(0)} s`);
