package billing

// Billing workspace (Revenue & Billing → Billing,
// docs/Revenue_Billing_Billing_Workspace_Improvement_Requirements.md): the
// folios with charges still to bill, grouped by the business that created
// them, with the next action of each one.
//
//   - pending billing: charges exist but the folio is still open and nobody
//     marked it ready;
//   - ready to invoice: the folio is closed (or marked ready) and every
//     validation passed;
//   - exception: closed or marked ready, but a blocking exception is open;
//   - invoiced: every charge is on an invoice (Invoices owns it from there);
//   - cancelled: the folio was cancelled after billing work started.
//
// Exceptions are derived from the folio, its charges and the bill-to party,
// never stored, so they clear once the data is fixed. What Finance prepared
// (bill-to, payment term, references, owner, ready, approval, acknowledged
// exceptions) is the billing record of the folio (billing.billing_records).
// Invoices are generated by CreateInvoice / IssueInvoice (number, AR
// transfer, accounting event, customer portal, PDF) and sent with the
// invoice template.

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"slices"
	"strconv"
	"strings"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/shopspring/decimal"

	"oneclub/internal/kernel/authz"
	"oneclub/internal/kernel/dbtx"
	"oneclub/internal/kernel/errs"
	"oneclub/internal/kernel/httpx"
	"oneclub/internal/kernel/id"
	"oneclub/internal/kernel/route"
	"oneclub/internal/platform/audit"
	"oneclub/internal/platform/handle"
	"oneclub/internal/platform/rules"
)

// Billing workspace statuses.
const (
	BillPending   = "pending_billing"
	BillReady     = "ready_to_invoice"
	BillException = "exception"
	BillInvoiced  = "invoiced"
	BillCancelled = "cancelled"
	BillSettled   = "settled" // nothing to bill (one folio only, never in the queue)
)

// Billing workspace permissions: preparing (review, prepare, adjust, resolve
// operational exceptions) and approving (high-value billing, adjustments,
// overrides, consolidation); above the executive threshold the General
// Manager / Director approves.
const (
	PermBillingPrepare          = "billing.billing.prepare"
	PermBillingApprove          = "billing.billing.approve"
	PermBillingApproveExecutive = "billing.billing.approve_executive"
)

// BillingWorkspacePolicy are the validation and approval thresholds of the
// billing workspace.
type BillingWorkspacePolicy struct {
	ApprovalThreshold          string `json:"approvalThreshold" doc:"Amounts to invoice from this value need the Finance Manager's approval (0 = never)"`
	ExecutiveApprovalThreshold string `json:"executiveApprovalThreshold" doc:"From this value the General Manager / Director approves (0 = never)"`
	DocumentThreshold          string `json:"documentThreshold" doc:"Company billing from this value needs a PO, contract or supporting document (0 = never)"`
	RequireCompanyNPWP         bool   `json:"requireCompanyNpwp" doc:"A company billed with tax needs its NPWP (tax invoice)"`
}

// DefaultBillingWorkspacePolicy: approval from Rp100 jt, executive from
// Rp500 jt, documents for company billing from Rp25 jt.
var DefaultBillingWorkspacePolicy = BillingWorkspacePolicy{ApprovalThreshold: "100000000", ExecutiveApprovalThreshold: "500000000",
	DocumentThreshold: "25000000", RequireCompanyNPWP: true}

func init() {
	rules.RegisterPolicy(rules.PolicyDef{Code: "billing.workspace", Category: "Credit Policies", Name: "Billing validation & approval",
		Description: "Approval thresholds of billing (Finance Manager, General Manager / Director) and when company billing needs NPWP and supporting documents",
		Default:     DefaultBillingWorkspacePolicy})
}

// LoadBillingWorkspacePolicy returns the billing workspace policy in force.
func LoadBillingWorkspacePolicy(ctx context.Context, q dbtx.Querier, property uuid.UUID) (BillingWorkspacePolicy, error) {
	p, _, err := rules.PolicyAt(ctx, q, "billing.workspace", property, DefaultBillingWorkspacePolicy)
	return p, err
}

// billingGroups maps a folio source to its business.
var billingGroups = []struct {
	key, label string
	sources    []string
}{
	{"golf", "Golf", []string{"golf_booking", "tournament", "golf_round", "walk_in", "bag_storage"}},
	{"resort", "Resort", []string{"reservation", "stay", "package_booking"}},
	{"events", "Events & Meetings", []string{"banquet_event", "quotation"}},
	{"membership", "Membership", []string{"membership_fee", "membership_renewal", "membership"}},
	{"sport", "Sport Club", []string{"sport_entry", "class_enrollment", "locker"}},
	{"fnb", "F&B & Retail", []string{"pos_order", "voucher_sale"}},
	{"other", "Other", nil},
}

func billingGroup(source string) string {
	for _, g := range billingGroups {
		if slices.Contains(g.sources, source) {
			return g.key
		}
	}
	return "other"
}

// ── exceptions ────────────────────────────────────────────────────────────

// Exception codes of the billing workspace.
var billingExceptionLabels = map[string]string{
	"missing_customer":            "Missing Customer",
	"missing_billing_entity":      "Missing Billing Entity",
	"missing_billing_address":     "Missing Billing Address",
	"missing_tax_information":     "Missing Tax Information",
	"invalid_tax_configuration":   "Invalid Tax Configuration",
	"pricing_mismatch":            "Pricing Mismatch",
	"unresolved_folio":            "Unresolved Folio",
	"duplicate_charge":            "Duplicate Charge",
	"missing_supporting_document": "Missing Supporting Document",
	"invalid_payment_term":        "Invalid Payment Term",
	"revenue_allocation_error":    "Revenue Allocation Error",
	"approval_required":           "Approval Required",
}

// BillingResolution is who acknowledged or overrode an exception.
type BillingResolution struct {
	Reason string    `json:"reason"`
	By     uuid.UUID `json:"by"`
	ByName string    `json:"byName"`
	At     time.Time `json:"at"`
}

// BillingException is one issue that stops (or may stop) invoicing.
type BillingException struct {
	Code     string `json:"code" enum:"missing_customer,missing_billing_entity,missing_billing_address,missing_tax_information,invalid_tax_configuration,pricing_mismatch,unresolved_folio,duplicate_charge,missing_supporting_document,invalid_payment_term,revenue_allocation_error,approval_required"`
	Label    string `json:"label"`
	Severity string `json:"severity" enum:"high,medium"`
	Message  string `json:"message"`
	// Resolution: fix = correct the data (Prepare Billing, adjustment, folio);
	// acknowledge = the accountant accepts it with a reason; override = the
	// Finance Manager overrides it with a reason; approve = the approver approves the billing.
	Resolution string             `json:"resolution" enum:"fix,acknowledge,override,approve"`
	Resolved   *BillingResolution `json:"resolved,omitempty" doc:"Acknowledged or overridden: no longer blocking"`
}

// ── queue ─────────────────────────────────────────────────────────────────

// BillingItem is a folio of the billing workspace with its next action.
type BillingItem struct {
	FolioID            uuid.UUID          `json:"folioId"`
	Number             string             `json:"number"`
	HolderName         string             `json:"holderName"`
	SourceType         string             `json:"sourceType"`
	SourceID           *uuid.UUID         `json:"sourceId"`
	SourceRef          *string            `json:"sourceRef"`
	Group              string             `json:"group" enum:"golf,resort,events,membership,sport,fnb,other"`
	FolioStatus        string             `json:"folioStatus" enum:"open,closed,cancelled"`
	CustomerID         *uuid.UUID         `json:"customerId"`
	CustomerName       *string            `json:"customerName"`
	CorporateAccountID *uuid.UUID         `json:"corporateAccountId"`
	BillTo             string             `json:"billTo" doc:"Who the invoice is addressed to; empty when nobody can be billed"`
	BillToKind         string             `json:"billToKind" enum:"company,customer,none"`
	Charges            string             `json:"charges"`
	Paid               string             `json:"paid" doc:"Payments received on the folio and on its invoice (not the transfer to AR)"`
	Deposit            string             `json:"deposit" doc:"Deposits / advances held or applied"`
	ToInvoice          string             `json:"toInvoice" doc:"Gross charges less deposits, payments and AR transfers"`
	TermsDays          int                `json:"termsDays" doc:"Payment term of the invoice (billing record or Credit Policies default)"`
	InvoiceID          *uuid.UUID         `json:"invoiceId"`
	InvoiceNumber      *string            `json:"invoiceNumber"`
	InvoiceStatus      *string            `json:"invoiceStatus" enum:"draft,issued,partially_paid,paid,overdue"`
	Outstanding        *string            `json:"outstanding" doc:"What the customer still owes on the invoice"`
	Status             string             `json:"status" enum:"pending_billing,ready_to_invoice,exception,invoiced,cancelled,settled"`
	CanInvoice         bool               `json:"canInvoice" doc:"No blocking exception: Generate Invoice is allowed"`
	Exceptions         []BillingException `json:"exceptions"`
	Blocking           int                `json:"blocking" doc:"Open exceptions that stop invoicing"`
	OwnerID            *uuid.UUID         `json:"ownerId"`
	OwnerName          *string            `json:"ownerName"`
	Prepared           bool               `json:"prepared" doc:"A billing record exists (Prepare Billing was saved)"`
	MarkedReady        bool               `json:"markedReady"`
	DueSince           time.Time          `json:"dueSince" doc:"When the folio became due for billing (closed, marked ready, or opened)"`
	ApprovedAt         *time.Time         `json:"approvedAt"`
	CreatedAt          time.Time          `json:"createdAt"`
}

// BillingGroupSummary is the workload of one business.
type BillingGroupSummary struct {
	Key           string `json:"key"`
	Label         string `json:"label"`
	TotalBillable string `json:"totalBillable" doc:"To invoice over pending, ready and exception folios"`
	Pending       int    `json:"pending"`
	Ready         int    `json:"ready"`
	ReadyAmount   string `json:"readyAmount"`
	Exceptions    int    `json:"exceptions"`
	Invoiced      int    `json:"invoiced"`
}

// BillingQueue is the billing workspace of a property.
type BillingQueue struct {
	Groups     []BillingGroupSummary `json:"groups"`
	Counts     map[string]int        `json:"counts" doc:"Folios per status over every business (before the status filter)"`
	Items      []BillingItem         `json:"items" doc:"One page of the filtered folios"`
	Total      int                   `json:"total" doc:"Folios matching the filters"`
	NextCursor string                `json:"nextCursor,omitempty"`
}

type billingRow struct {
	FolioID         uuid.UUID       `db:"folio_id"`
	Number          string          `db:"number"`
	HolderName      string          `db:"holder_name"`
	SourceType      string          `db:"source_type"`
	SourceID        *uuid.UUID      `db:"source_id"`
	SourceRef       *string         `db:"source_ref"`
	FolioStatus     string          `db:"folio_status"`
	CreatedAt       time.Time       `db:"created_at"`
	ClosedAt        *time.Time      `db:"closed_at"`
	CorporateName   *string         `db:"corporate_name"`
	CustomerID      *uuid.UUID      `db:"customer_id"`
	CustomerName    *string         `db:"customer_name"`
	CorporateID     *uuid.UUID      `db:"corporate_account_id"`
	CompanyName     *string         `db:"company_name"`
	CompanyStatus   *string         `db:"company_status"`
	CompanyArchived bool            `db:"company_archived"`
	BillToName      *string         `db:"bill_to_name"`
	BillToAddress   *string         `db:"bill_to_address"`
	BillToNPWP      *string         `db:"bill_to_npwp"`
	HasRecord       bool            `db:"has_record"`
	RecordStatus    *string         `db:"record_status"`
	TermsDays       *int            `db:"terms_days"`
	OwnerID         *uuid.UUID      `db:"owner_id"`
	OwnerName       *string         `db:"owner_name"`
	ReadyAt         *time.Time      `db:"ready_at"`
	ApprovedAmount  *string         `db:"approved_amount"`
	ApprovedAt      *time.Time      `db:"approved_at"`
	Resolved        json.RawMessage `db:"resolved"`
	HasDocument     bool            `db:"has_document"`
	Charges         string          `db:"charges"`
	Uninvoiced      string          `db:"uninvoiced"`
	UninvoicedLines int             `db:"uninvoiced_lines"`
	UninvoicedTax   string          `db:"uninvoiced_tax"`
	BadTax          int             `db:"bad_tax"`
	BadPrice        int             `db:"bad_price"`
	BadAlloc        int             `db:"bad_alloc"`
	Duplicates      int             `db:"duplicates"`
	Paid            string          `db:"paid"`
	Deposit         string          `db:"deposit"`
	ToInvoice       string          `db:"to_invoice"`
	PendingMoney    int             `db:"pending_money"`
	Unapproved      int             `db:"unapproved"`
	InvoiceID       *uuid.UUID      `db:"invoice_id"`
	InvoiceNumber   *string         `db:"invoice_number"`
	InvoiceStatus   *string         `db:"invoice_status"`
	Outstanding     *string         `db:"outstanding"`
}

// billingRows loads the folios of the workspace (one folio when folio is set,
// whatever its state).
func billingRows(ctx context.Context, q dbtx.Querier, property uuid.UUID, folio *uuid.UUID) ([]billingRow, error) {
	components := append(append([]string{}, RevenueComponents...), chargeTypes...)
	return handle.List[billingRow](q.Query(ctx, `WITH b AS MATERIALIZED ( -- computed once (the balance is filtered, shown and sorted)
		  SELECT f.id, f.number, f.holder_name, f.source_type, f.source_id, f.source_ref, f.status, f.created_at, f.closed_at, f.corporate_name,
		    f.customer_id AS folio_customer, f.corporate_account_id AS folio_corporate,
		    coalesce(l.charges, 0) AS charges, coalesce(l.uninvoiced, 0) AS uninvoiced, coalesce(l.uninvoiced_lines, 0) AS uninvoiced_lines,
		    coalesce(l.uninvoiced_tax, 0) AS uninvoiced_tax, coalesce(l.bad_tax, 0) AS bad_tax, coalesce(l.bad_price, 0) AS bad_price,
		    coalesce(l.bad_alloc, 0) AS bad_alloc,
		    -- the same source posted twice (golf player, room night …) and not reversed
		    (SELECT count(*) FROM (SELECT 1 FROM billing.folio_lines x WHERE x.folio_id = f.id AND x.voided_at IS NULL AND x.invoice_id IS NULL
		      AND x.reference_id IS NOT NULL AND coalesce(x.reference_type, '') NOT LIKE 'billing.%'
		      GROUP BY x.reference_type, x.reference_id, x.charge_type HAVING count(*) FILTER (WHERE x.total > 0) > 1 AND sum(x.total) > max(x.total)) g) AS duplicates,
		    coalesce((SELECT sum(amount - refunded_amount) FROM billing.payments p WHERE p.folio_id = f.id AND p.status IN ('completed', 'refunded')
		      AND p.purpose = 'settlement' AND p.method_type NOT IN ('member_account', 'folio_transfer')), 0) AS paid,
		    coalesce((SELECT sum(CASE WHEN d.status = 'held' THEN d.amount ELSE d.applied_amount END) FROM billing.deposits d
		      WHERE d.folio_id = f.id AND d.status IN ('held', 'applied')), 0) AS deposit,
		    -- moved to an AR account (invoice issue, charge to account) or another folio: billed, not paid
		    coalesce((SELECT sum(amount - refunded_amount) FROM billing.payments p WHERE p.folio_id = f.id AND p.status IN ('completed', 'refunded')
		      AND p.purpose = 'settlement' AND p.method_type IN ('member_account', 'folio_transfer')), 0) AS transferred,
		    (SELECT count(*) FROM billing.payments p WHERE p.folio_id = f.id AND p.status = 'pending')
		      + (SELECT count(*) FROM billing.refunds x WHERE x.folio_id = f.id AND x.status = 'pending') AS pending_money,
		    (SELECT count(*) FROM billing.billing_adjustments a WHERE a.folio_id = f.id AND a.approved_at IS NULL) AS unapproved,
		    i.id AS invoice_id, i.number AS invoice_number, i.status AS invoice_status, coalesce(i.paid_amount, 0) AS invoice_paid,
		    CASE WHEN i.status = 'draft' THEN 0 ELSE i.total - i.paid_amount - i.credited_amount - i.written_off_amount END AS outstanding
		  FROM billing.folios f
		  LEFT JOIN LATERAL (SELECT sum(x.total) AS charges, sum(x.total) FILTER (WHERE x.invoice_id IS NULL) AS uninvoiced,
		      count(*) FILTER (WHERE x.invoice_id IS NULL) AS uninvoiced_lines, sum(x.tax_amount) FILTER (WHERE x.invoice_id IS NULL) AS uninvoiced_tax,
		      count(*) FILTER (WHERE x.invoice_id IS NULL AND (abs(x.net_amount + x.tax_amount + x.service_amount - x.total) > 1
		        OR (x.net_amount > 0 AND (x.tax_amount < 0 OR x.service_amount < 0)))) AS bad_tax,
		      -- quantity × unit price matches neither the net nor the all-in amount
		      count(*) FILTER (WHERE x.invoice_id IS NULL AND x.charge_type <> 'discount' AND coalesce(x.reference_type, '') NOT LIKE 'billing.%'
		        AND abs(x.quantity * x.unit_price - x.net_amount) > 1 AND abs(x.quantity * x.unit_price - x.total) > 1) AS bad_price,
		      count(*) FILTER (WHERE x.invoice_id IS NULL AND (x.business_line <> ALL($3::text[])
		        OR coalesce(x.revenue_component, x.charge_type) <> ALL($4::text[]))) AS bad_alloc
		    FROM billing.folio_lines x WHERE x.folio_id = f.id AND x.voided_at IS NULL) l ON true
		  LEFT JOIN LATERAL (SELECT id, number, status, total, paid_amount, credited_amount, written_off_amount FROM billing.invoices v
		    WHERE v.status <> 'void' AND (v.folio_id = f.id OR v.id IN (SELECT y.invoice_id FROM billing.folio_lines y WHERE y.folio_id = f.id AND y.invoice_id IS NOT NULL))
		    ORDER BY v.created_at DESC LIMIT 1) i ON true
		  WHERE f.property_id = $1 AND f.source_type <> 'manual_invoice' AND ($2::uuid IS NULL OR f.id = $2)
		    AND (f.status IN ('open', 'closed') OR $2::uuid IS NOT NULL OR EXISTS (SELECT 1 FROM billing.billing_records r WHERE r.folio_id = f.id)))
		SELECT b.id AS folio_id, b.number, b.holder_name, b.source_type, b.source_id, b.source_ref, b.status AS folio_status, b.created_at, b.closed_at,
		  b.corporate_name, coalesce(r.customer_id, b.folio_customer) AS customer_id, cu.name AS customer_name,
		  coalesce(r.corporate_account_id, b.folio_corporate) AS corporate_account_id, c.name AS company_name, c.status AS company_status,
		  c.archived_at IS NOT NULL AS company_archived, nullif(r.bill_to_name, '') AS bill_to_name,
		  coalesce(nullif(r.bill_to_address, ''), CASE WHEN c.id IS NOT NULL THEN c.address ELSE cu.address END) AS bill_to_address,
		  coalesce(nullif(r.bill_to_npwp, ''), c.npwp) AS bill_to_npwp,
		  r.id IS NOT NULL AS has_record, r.status AS record_status, r.terms_days, r.owner_id, u.full_name AS owner_name, r.ready_at,
		  trim_scale(r.approved_amount)::text AS approved_amount, r.approved_at, coalesce(r.resolved, '{}'::jsonb) AS resolved,
		  (coalesce(r.customer_po, '') <> '' OR coalesce(r.contract_ref, '') <> '' OR coalesce(cardinality(r.attachment_file_ids), 0) > 0) AS has_document,
		  trim_scale(b.charges)::text AS charges, trim_scale(b.uninvoiced)::text AS uninvoiced, b.uninvoiced_lines::int AS uninvoiced_lines,
		  trim_scale(b.uninvoiced_tax)::text AS uninvoiced_tax, b.bad_tax::int AS bad_tax, b.bad_price::int AS bad_price, b.bad_alloc::int AS bad_alloc,
		  b.duplicates::int AS duplicates, trim_scale(b.paid + b.invoice_paid)::text AS paid, trim_scale(b.deposit)::text AS deposit,
		  trim_scale(greatest(b.charges - b.paid - b.deposit - b.transferred, 0))::text AS to_invoice, b.pending_money::int AS pending_money,
		  b.unapproved::int AS unapproved, b.invoice_id, b.invoice_number, b.invoice_status, trim_scale(b.outstanding)::text AS outstanding
		FROM b
		LEFT JOIN billing.billing_records r ON r.folio_id = b.id
		LEFT JOIN crm.corporate_accounts c ON c.id = coalesce(r.corporate_account_id, b.folio_corporate)
		LEFT JOIN crm.customers cu ON cu.id = coalesce(r.customer_id, b.folio_customer)
		LEFT JOIN platform.users u ON u.id = r.owner_id
		WHERE $2::uuid IS NOT NULL OR b.charges - b.paid - b.deposit - b.transferred > 0 OR b.invoice_id IS NOT NULL OR r.id IS NOT NULL
		ORDER BY greatest(b.charges - b.paid - b.deposit - b.transferred, 0) DESC, b.created_at DESC`, property, folio, BusinessLines, components))
}

// billingContext caches what the exceptions of many folios share.
type billingContext struct {
	policy  BillingWorkspacePolicy
	credit  CreditPolicy
	balance map[uuid.UUID]*Account // city ledger per company
}

func newBillingContext(ctx context.Context, q dbtx.Querier, property uuid.UUID) (*billingContext, error) {
	pol, err := LoadBillingWorkspacePolicy(ctx, q, property)
	if err != nil {
		return nil, err
	}
	cp, _, err := LoadCreditPolicy(ctx, q, property)
	if err != nil {
		return nil, err
	}
	return &billingContext{policy: pol, credit: cp, balance: map[uuid.UUID]*Account{}}, nil
}

// companyAccount is the city ledger of a company (a not yet opened one is
// empty and active).
func (bc *billingContext) companyAccount(ctx context.Context, q dbtx.Querier, property, company uuid.UUID) (Account, error) {
	if a, ok := bc.balance[company]; ok {
		return *a, nil
	}
	a := Account{AccountType: "corporate", Status: "active", Balance: "0"}
	var aid uuid.UUID
	err := q.QueryRow(ctx, `SELECT id FROM billing.customer_accounts WHERE property_id = $1 AND corporate_account_id = $2 AND account_type = 'corporate'`,
		property, company).Scan(&aid)
	switch {
	case err == nil:
		if a, err = GetAccount(ctx, q, aid); err != nil {
			return a, err
		}
	case !dbtx.IsNoRows(err):
		return a, err
	}
	bc.balance[company] = &a
	return a, nil
}

// evaluate turns a folio row into a workspace item with its exceptions and
// status.
func (bc *billingContext) evaluate(ctx context.Context, q dbtx.Querier, property uuid.UUID, r billingRow) (BillingItem, error) {
	it := BillingItem{FolioID: r.FolioID, Number: r.Number, HolderName: r.HolderName, SourceType: r.SourceType, SourceID: r.SourceID, SourceRef: r.SourceRef,
		Group: billingGroup(r.SourceType), FolioStatus: r.FolioStatus, CustomerID: r.CustomerID, CustomerName: r.CustomerName, CorporateAccountID: r.CorporateID,
		Charges: r.Charges, Paid: r.Paid, Deposit: r.Deposit, ToInvoice: r.ToInvoice, InvoiceID: r.InvoiceID, InvoiceNumber: r.InvoiceNumber,
		InvoiceStatus: r.InvoiceStatus, Outstanding: r.Outstanding, OwnerID: r.OwnerID, OwnerName: r.OwnerName, Prepared: r.HasRecord,
		MarkedReady: r.RecordStatus != nil && *r.RecordStatus == "ready", ApprovedAt: r.ApprovedAt, CreatedAt: r.CreatedAt, Exceptions: []BillingException{}}
	switch {
	case r.CorporateID != nil && r.CompanyName != nil:
		it.BillTo, it.BillToKind = *r.CompanyName, "company"
	case r.CustomerID != nil && r.CustomerName != nil:
		it.BillTo, it.BillToKind = *r.CustomerName, "customer"
	default:
		it.BillToKind = "none"
	}
	if r.BillToName != nil && it.BillToKind != "none" {
		it.BillTo = *r.BillToName
	}
	it.TermsDays = 0
	if r.CorporateID != nil {
		it.TermsDays = bc.credit.PaymentTermDays
	}
	if r.TermsDays != nil {
		it.TermsDays = *r.TermsDays
	}
	it.DueSince = r.CreatedAt
	if r.ClosedAt != nil {
		it.DueSince = *r.ClosedAt
	}
	if r.ReadyAt != nil && (r.ClosedAt == nil || r.ReadyAt.Before(*r.ClosedAt)) {
		it.DueSince = *r.ReadyAt
	}
	toInvoice := dec(r.ToInvoice)
	billable := toInvoice.IsPositive() && r.UninvoicedLines > 0
	switch {
	case r.FolioStatus == "cancelled" || (r.RecordStatus != nil && *r.RecordStatus == "cancelled"):
		it.Status = BillCancelled
		return it, nil
	case !billable && r.InvoiceID != nil:
		it.Status = BillInvoiced
		return it, nil
	case !billable:
		it.Status = BillSettled
		return it, nil
	}
	resolved := map[string]BillingResolution{}
	_ = json.Unmarshal(r.Resolved, &resolved)
	add := func(code, severity, resolution, msg string) {
		e := BillingException{Code: code, Label: billingExceptionLabels[code], Severity: severity, Resolution: resolution, Message: msg}
		if x, ok := resolved[code]; ok && resolution != "fix" && resolution != "approve" {
			e.Resolved = &x
		}
		it.Exceptions = append(it.Exceptions, e)
	}
	company := r.CorporateID != nil
	if r.CustomerID == nil && !company {
		add("missing_customer", "high", "fix", "Nobody to bill: link a customer or a company to the billing")
	}
	switch {
	case company && (r.CompanyArchived || (r.CompanyStatus != nil && *r.CompanyStatus != "active")):
		add("missing_billing_entity", "high", "fix", fmt.Sprintf("Company %s is inactive: bill another company or the guest", deref(r.CompanyName)))
	case !company && r.CorporateName != nil && strings.TrimSpace(*r.CorporateName) != "":
		add("missing_billing_entity", "high", "override", fmt.Sprintf("The folio names company %q, which is not linked to a corporate account", *r.CorporateName))
	}
	if company && strings.TrimSpace(deref(r.BillToAddress)) == "" {
		add("missing_billing_address", "high", "fix", "The company has no billing address")
	}
	if company && bc.policy.RequireCompanyNPWP && dec(r.UninvoicedTax).IsPositive() && strings.TrimSpace(deref(r.BillToNPWP)) == "" {
		add("missing_tax_information", "high", "override", "The company has no NPWP for the tax invoice (e-Faktur)")
	}
	if r.BadTax > 0 {
		add("invalid_tax_configuration", "high", "fix", fmt.Sprintf("%d charge(s) where net + service + tax does not equal the total", r.BadTax))
	}
	if r.BadPrice > 0 {
		add("pricing_mismatch", "medium", "acknowledge", fmt.Sprintf("%d charge(s) where quantity × unit price does not match the amount", r.BadPrice))
	}
	if r.PendingMoney > 0 {
		add("unresolved_folio", "high", "override", fmt.Sprintf("%d payment(s) or refund(s) on the folio are still pending", r.PendingMoney))
	}
	if r.Duplicates > 0 {
		add("duplicate_charge", "medium", "acknowledge", fmt.Sprintf("%d source transaction(s) charged more than once", r.Duplicates))
	}
	if company && !r.HasDocument {
		if t := dec(bc.policy.DocumentThreshold); t.IsPositive() && toInvoice.GreaterThanOrEqual(t) {
			add("missing_supporting_document", "medium", "acknowledge", "Company billing of this value needs a customer PO, contract or supporting document")
		}
	}
	if company {
		a, err := bc.companyAccount(ctx, q, property, *r.CorporateID)
		if err != nil {
			return it, err
		}
		if err := CheckCredit(ctx, q, property, a, toInvoice); err != nil {
			var e *errs.Error
			if !errors.As(err, &e) || e.Kind != errs.KindConflict {
				return it, err
			}
			add("invalid_payment_term", "high", "fix", "Credit term not available: "+e.Message+"; request a credit override in Corporate Billing")
		}
	} else if it.TermsDays > 0 {
		add("invalid_payment_term", "medium", "acknowledge", fmt.Sprintf("A %d-day credit term for an individual; individuals normally pay at once", it.TermsDays))
	}
	if r.BadAlloc > 0 {
		add("revenue_allocation_error", "high", "fix", fmt.Sprintf("%d charge(s) without a valid business line or revenue component", r.BadAlloc))
	}
	if level := bc.approvalLevel(toInvoice); level != "" || r.Unapproved > 0 {
		approved := r.ApprovedAmount != nil && dec(*r.ApprovedAmount).Equal(toInvoice) && r.Unapproved == 0
		if !approved {
			msg := "Adjustments wait for the Finance Manager's approval"
			if level != "" {
				who := "the Finance Manager"
				if level == "executive" {
					who = "the General Manager / Director"
				}
				msg = fmt.Sprintf("High-value billing (%s) needs the approval of %s", toInvoice.StringFixed(0), who)
			}
			add("approval_required", "high", "approve", msg)
		}
	}
	for _, e := range it.Exceptions {
		if e.Resolved == nil {
			it.Blocking++
		}
	}
	it.CanInvoice = it.Blocking == 0
	due := r.FolioStatus == "closed" || it.MarkedReady
	switch {
	case !due:
		it.Status = BillPending
	case it.Blocking > 0:
		it.Status = BillException
	default:
		it.Status = BillReady
	}
	return it, nil
}

// approvalLevel is "", "manager" or "executive" for an amount to invoice.
func (bc *billingContext) approvalLevel(amount decimal.Decimal) string {
	if t := dec(bc.policy.ExecutiveApprovalThreshold); t.IsPositive() && amount.GreaterThanOrEqual(t) {
		return "executive"
	}
	if t := dec(bc.policy.ApprovalThreshold); t.IsPositive() && amount.GreaterThanOrEqual(t) {
		return "manager"
	}
	return ""
}

// BillingItems evaluates the workspace folios (one folio when folio is set).
func BillingItems(ctx context.Context, q dbtx.Querier, property uuid.UUID, folio *uuid.UUID) ([]BillingItem, error) {
	rows, err := billingRows(ctx, q, property, folio)
	if err != nil {
		return nil, err
	}
	bc, err := newBillingContext(ctx, q, property)
	if err != nil {
		return nil, err
	}
	out := make([]BillingItem, 0, len(rows))
	for _, r := range rows {
		it, err := bc.evaluate(ctx, q, property, r)
		if err != nil {
			return nil, err
		}
		if folio == nil && it.Status == BillSettled {
			continue
		}
		out = append(out, it)
	}
	return out, nil
}

// BillingItemOf evaluates one folio.
func BillingItemOf(ctx context.Context, q dbtx.Querier, property, folio uuid.UUID) (BillingItem, error) {
	items, err := BillingItems(ctx, q, property, &folio)
	if err != nil {
		return BillingItem{}, err
	}
	if len(items) == 0 {
		return BillingItem{}, errs.NotFound("folio")
	}
	return items[0], nil
}

// Queue lists the billing workspace with the per-business summary.
func Queue(ctx context.Context, q dbtx.Querier, property uuid.UUID, status, group, owner, search string, offset, size int) (BillingQueue, error) {
	items, err := BillingItems(ctx, q, property, nil)
	if err != nil {
		return BillingQueue{}, err
	}
	out := BillingQueue{Groups: []BillingGroupSummary{}, Items: []BillingItem{}, Counts: map[string]int{}}
	sums := map[string]*BillingGroupSummary{}
	amounts := map[string][2]decimal.Decimal{}
	for _, g := range billingGroups {
		sums[g.key] = &BillingGroupSummary{Key: g.key, Label: g.label}
	}
	search = strings.ToLower(strings.TrimSpace(search))
	for _, it := range items {
		g, a := sums[it.Group], amounts[it.Group]
		v := dec(it.ToInvoice)
		switch it.Status {
		case BillPending:
			g.Pending++
			a[0] = a[0].Add(v)
		case BillReady:
			g.Ready++
			a[0], a[1] = a[0].Add(v), a[1].Add(v)
		case BillException:
			g.Exceptions++
			a[0] = a[0].Add(v)
		case BillInvoiced:
			g.Invoiced++
		}
		amounts[it.Group] = a
		if group != "" && group != it.Group {
			continue
		}
		if owner != "" && (it.OwnerID == nil || it.OwnerID.String() != owner) {
			continue
		}
		if search != "" && !strings.Contains(strings.ToLower(it.Number+" "+it.HolderName+" "+it.BillTo+" "+deref(it.SourceRef)+" "+deref(it.InvoiceNumber)), search) {
			continue
		}
		out.Counts[it.Status]++
		if status != "" && status != it.Status {
			continue
		}
		if out.Total >= offset && len(out.Items) < size {
			out.Items = append(out.Items, it)
		}
		out.Total++
	}
	for _, g := range billingGroups {
		s, a := sums[g.key], amounts[g.key]
		if s.Pending+s.Ready+s.Exceptions+s.Invoiced == 0 {
			continue
		}
		s.TotalBillable, s.ReadyAmount = a[0].String(), a[1].String()
		out.Groups = append(out.Groups, *s)
	}
	if offset+size < out.Total {
		out.NextCursor = httpx.EncodeCursor("o:" + strconv.Itoa(offset+size))
	}
	return out, nil
}

// ── billing record ────────────────────────────────────────────────────────

// BillingRecord is what Finance prepared on a folio.
type BillingRecord struct {
	CustomerID         *uuid.UUID  `json:"customerId" db:"customer_id" doc:"Bill to another customer than the folio's"`
	CorporateAccountID *uuid.UUID  `json:"corporateAccountId" db:"corporate_account_id" doc:"Bill to the company"`
	BillToName         *string     `json:"billToName" db:"bill_to_name"`
	BillToAddress      *string     `json:"billToAddress" db:"bill_to_address"`
	BillToNPWP         *string     `json:"billToNpwp" db:"bill_to_npwp"`
	BillToEmail        *string     `json:"billToEmail" db:"bill_to_email"`
	BillToPhone        *string     `json:"billToPhone" db:"bill_to_phone"`
	TermsDays          *int        `json:"termsDays" db:"terms_days" doc:"null: Credit Policies default"`
	CustomerPO         *string     `json:"customerPo" db:"customer_po"`
	ContractRef        *string     `json:"contractRef" db:"contract_ref"`
	BillingRef         *string     `json:"billingRef" db:"billing_ref"`
	Notes              *string     `json:"notes" db:"notes" doc:"Printed on the invoice"`
	InternalNotes      *string     `json:"internalNotes" db:"internal_notes"`
	AttachmentFileIDs  []uuid.UUID `json:"attachmentFileIds" db:"attachment_file_ids"`
	ReadyAt            *time.Time  `json:"readyAt" db:"ready_at"`
	ReadyByName        *string     `json:"readyByName" db:"ready_by_name"`
	ApprovedAmount     *string     `json:"approvedAmount" db:"approved_amount"`
	ApprovedAt         *time.Time  `json:"approvedAt" db:"approved_at"`
	ApprovedByName     *string     `json:"approvedByName" db:"approved_by_name"`
	Version            int         `json:"version" db:"version"`
}

// BillingCheck is one line of the Ready to Invoice validation.
type BillingCheck struct {
	Key    string `json:"key"`
	Label  string `json:"label"`
	OK     bool   `json:"ok"`
	Detail string `json:"detail,omitempty"`
}

// BillingBreakdown is the calculation of the amount to invoice.
type BillingBreakdown struct {
	GrossCharges  string `json:"grossCharges" doc:"Net charges before discounts"`
	Discount      string `json:"discount"`
	ServiceCharge string `json:"serviceCharge"`
	Tax           string `json:"tax"`
	Deposit       string `json:"deposit" doc:"Deposits / advances held or applied"`
	Payments      string `json:"payments"`
	Transferred   string `json:"transferred" doc:"Already moved to an AR account (earlier invoices, charge to account)"`
	ToInvoice     string `json:"toInvoice"`
}

// BillingLine is a charge of the folio.
type BillingLine struct {
	ID               uuid.UUID  `json:"id" db:"id"`
	ChargeType       string     `json:"chargeType" db:"charge_type"`
	Description      string     `json:"description" db:"description"`
	BusinessLine     string     `json:"businessLine" db:"business_line"`
	RevenueComponent string     `json:"revenueComponent" db:"revenue_component"`
	Quantity         string     `json:"quantity" db:"quantity"`
	UnitPrice        string     `json:"unitPrice" db:"unit_price"`
	NetAmount        string     `json:"netAmount" db:"net_amount"`
	ServiceAmount    string     `json:"serviceAmount" db:"service_amount"`
	TaxAmount        string     `json:"taxAmount" db:"tax_amount"`
	Total            string     `json:"total" db:"total"`
	ReferenceType    *string    `json:"referenceType" db:"reference_type"`
	ReferenceID      *uuid.UUID `json:"referenceId" db:"reference_id"`
	InvoiceID        *uuid.UUID `json:"invoiceId" db:"invoice_id"`
	PostedAt         time.Time  `json:"postedAt" db:"posted_at"`
}

// BillingAdjustment is a change of a charge made in the billing workspace.
type BillingAdjustment struct {
	ID             uuid.UUID  `json:"id" db:"id"`
	LineID         uuid.UUID  `json:"lineId" db:"folio_line_id"`
	LineLabel      string     `json:"lineLabel" db:"line_label"`
	Kind           string     `json:"kind" db:"kind" enum:"quantity,price,discount,service_charge,tax,revenue_allocation"`
	PreviousValue  string     `json:"previousValue" db:"previous_value"`
	NewValue       string     `json:"newValue" db:"new_value"`
	Amount         string     `json:"amount" db:"amount" doc:"Change of the amount to invoice"`
	Reason         string     `json:"reason" db:"reason"`
	Reference      *string    `json:"reference" db:"reference"`
	CreatedAt      time.Time  `json:"createdAt" db:"created_at"`
	CreatedByName  *string    `json:"createdByName" db:"created_by_name"`
	ApprovedAt     *time.Time `json:"approvedAt" db:"approved_at"`
	ApprovedByName *string    `json:"approvedByName" db:"approved_by_name"`
}

// BillingHistoryEntry is one step from the operational charge to the invoice.
type BillingHistoryEntry struct {
	At      time.Time  `json:"at" db:"at"`
	Kind    string     `json:"kind" db:"kind"`
	Summary string     `json:"summary" db:"summary"`
	Actor   *string    `json:"actor" db:"actor"`
	Amount  *string    `json:"amount" db:"amount"`
	Ref     *uuid.UUID `json:"ref" db:"ref" doc:"Invoice of invoice entries"`
}

// BillingRecordDetail is the Review / Prepare Billing view of a folio.
type BillingRecordDetail struct {
	Item        BillingItem           `json:"item"`
	Record      BillingRecord         `json:"record"`
	Checks      []BillingCheck        `json:"checks"`
	Breakdown   BillingBreakdown      `json:"breakdown"`
	Lines       []BillingLine         `json:"lines"`
	Deposits    []Deposit             `json:"deposits"`
	Adjustments []BillingAdjustment   `json:"adjustments"`
	History     []BillingHistoryEntry `json:"history"`
	Currency    string                `json:"currency"`
	BusinessDay string                `json:"businessDate" doc:"Invoice date if generated today"`
	Approval    string                `json:"approval" enum:",manager,executive" doc:"Approval level the amount needs"`
}

// checkMap maps the validation list to the exceptions that fail it.
var checkMap = []struct{ key, label string }{
	{"customer", "Customer valid"}, {"bill_to", "Bill To valid"}, {"address", "Billing address valid"}, {"charges", "Charges validated"},
	{"tax", "Tax calculated"}, {"deposit", "Deposit applied"}, {"term", "Payment term available"}, {"allocation", "Revenue allocation available"},
	{"exceptions", "No blocking exception"},
}

var checkOf = map[string]string{
	"missing_customer": "customer", "missing_billing_entity": "bill_to", "missing_billing_address": "address", "pricing_mismatch": "charges",
	"duplicate_charge": "charges", "unresolved_folio": "charges", "missing_tax_information": "tax", "invalid_tax_configuration": "tax",
	"invalid_payment_term": "term", "revenue_allocation_error": "allocation",
}

// GetBillingRecord loads the Review / Prepare Billing view of a folio.
func GetBillingRecord(ctx context.Context, q dbtx.Querier, property, folio uuid.UUID) (BillingRecordDetail, error) {
	it, err := BillingItemOf(ctx, q, property, folio)
	if err != nil {
		return BillingRecordDetail{}, err
	}
	d := BillingRecordDetail{Item: it, Record: BillingRecord{AttachmentFileIDs: []uuid.UUID{}}}
	rec, err := handle.List[BillingRecord](q.Query(ctx, `SELECT r.customer_id, r.corporate_account_id, r.bill_to_name, r.bill_to_address, r.bill_to_npwp, r.bill_to_email,
		r.bill_to_phone, r.terms_days, r.customer_po, r.contract_ref, r.billing_ref, r.notes, r.internal_notes, r.attachment_file_ids, r.ready_at,
		ru.full_name AS ready_by_name, trim_scale(r.approved_amount)::text AS approved_amount, r.approved_at, au.full_name AS approved_by_name, r.version
		FROM billing.billing_records r LEFT JOIN platform.users ru ON ru.id = r.ready_by LEFT JOIN platform.users au ON au.id = r.approved_by
		WHERE r.folio_id = $1`, folio))
	if err != nil {
		return d, err
	}
	if len(rec) == 1 {
		d.Record = rec[0]
		if d.Record.AttachmentFileIDs == nil {
			d.Record.AttachmentFileIDs = []uuid.UUID{}
		}
	}
	if d.Lines, err = handle.List[BillingLine](q.Query(ctx, `SELECT id, charge_type, description, business_line, coalesce(revenue_component, charge_type) AS revenue_component,
		trim_scale(quantity)::text AS quantity, trim_scale(unit_price)::text AS unit_price, trim_scale(net_amount)::text AS net_amount,
		trim_scale(service_amount)::text AS service_amount, trim_scale(tax_amount)::text AS tax_amount, trim_scale(total)::text AS total,
		reference_type, reference_id, invoice_id, posted_at FROM billing.folio_lines WHERE folio_id = $1 AND voided_at IS NULL ORDER BY posted_at, id`, folio)); err != nil {
		return d, err
	}
	gross, disc, svc, tax := decimal.Zero, decimal.Zero, decimal.Zero, decimal.Zero
	for _, l := range d.Lines {
		if l.InvoiceID != nil {
			continue
		}
		net := dec(l.NetAmount)
		if l.ChargeType == "discount" || net.IsNegative() {
			disc = disc.Sub(net)
		} else {
			gross = gross.Add(net)
		}
		svc, tax = svc.Add(dec(l.ServiceAmount)), tax.Add(dec(l.TaxAmount))
	}
	var paid, deposit, transferred string
	if err := q.QueryRow(ctx, `SELECT f.currency,
		coalesce((SELECT sum(amount - refunded_amount) FROM billing.payments p WHERE p.folio_id = f.id AND p.status IN ('completed', 'refunded')
		  AND p.purpose = 'settlement' AND p.method_type NOT IN ('member_account', 'folio_transfer')), 0)::text,
		coalesce((SELECT sum(CASE WHEN d.status = 'held' THEN d.amount ELSE d.applied_amount END) FROM billing.deposits d
		  WHERE d.folio_id = f.id AND d.status IN ('held', 'applied')), 0)::text,
		coalesce((SELECT sum(amount - refunded_amount) FROM billing.payments p WHERE p.folio_id = f.id AND p.status IN ('completed', 'refunded')
		  AND p.purpose = 'settlement' AND p.method_type IN ('member_account', 'folio_transfer')), 0)::text
		FROM billing.folios f WHERE f.id = $1`, folio).Scan(&d.Currency, &paid, &deposit, &transferred); err != nil {
		return d, err
	}
	pl := places(d.Currency)
	d.Breakdown = BillingBreakdown{GrossCharges: gross.StringFixed(pl), Discount: disc.StringFixed(pl), ServiceCharge: svc.StringFixed(pl), Tax: tax.StringFixed(pl),
		Deposit: dec(deposit).StringFixed(pl), Payments: dec(paid).StringFixed(pl), Transferred: dec(transferred).StringFixed(pl),
		ToInvoice: dec(it.ToInvoice).StringFixed(pl)}
	drs, err := q.Query(ctx, `SELECT id, number, folio_id, payment_id, amount::text, applied_amount::text, currency, status, applied_at, created_at
		FROM billing.deposits WHERE folio_id = $1 ORDER BY created_at`, folio)
	if err != nil {
		return d, err
	}
	d.Deposits = []Deposit{}
	for drs.Next() {
		var x Deposit
		if err := drs.Scan(&x.ID, &x.Number, &x.FolioID, &x.PaymentID, &x.Amount, &x.AppliedAmount, &x.Currency, &x.Status, &x.AppliedAt, &x.CreatedAt); err != nil {
			drs.Close()
			return d, err
		}
		d.Deposits = append(d.Deposits, x)
	}
	drs.Close()
	if d.Adjustments, err = handle.List[BillingAdjustment](q.Query(ctx, `SELECT a.id, a.folio_line_id, l.description AS line_label, a.kind, a.previous_value,
		a.new_value, trim_scale(a.amount)::text AS amount, a.reason, a.reference, a.created_at, cu.full_name AS created_by_name, a.approved_at,
		au.full_name AS approved_by_name
		FROM billing.billing_adjustments a JOIN billing.folio_lines l ON l.id = a.folio_line_id
		LEFT JOIN platform.users cu ON cu.id = a.created_by LEFT JOIN platform.users au ON au.id = a.approved_by
		WHERE a.folio_id = $1 ORDER BY a.created_at DESC`, folio)); err != nil {
		return d, err
	}
	if d.History, err = billingHistory(ctx, q, folio); err != nil {
		return d, err
	}
	failed := map[string]string{}
	for _, e := range it.Exceptions {
		if e.Resolved == nil {
			if k, ok := checkOf[e.Code]; ok && failed[k] == "" {
				failed[k] = e.Message
			}
		}
	}
	if it.Blocking > 0 {
		failed["exceptions"] = fmt.Sprintf("%d blocking exception(s)", it.Blocking)
	}
	held := decimal.Zero
	for _, x := range d.Deposits {
		if x.Status == "held" {
			held = held.Add(dec(x.Amount).Sub(dec(x.AppliedAmount)))
		}
	}
	for _, c := range checkMap {
		ch := BillingCheck{Key: c.key, Label: c.label, OK: failed[c.key] == "", Detail: failed[c.key]}
		if c.key == "deposit" && held.IsPositive() {
			ch.Detail = "Held deposits of " + held.StringFixed(pl) + " are applied when the invoice is issued"
		}
		d.Checks = append(d.Checks, ch)
	}
	if bc, err := newBillingContext(ctx, q, property); err == nil {
		d.Approval = bc.approvalLevel(dec(it.ToInvoice))
	} else {
		return d, err
	}
	day, err := CurrentBusinessDate(ctx, q, property)
	if err != nil {
		return d, err
	}
	d.BusinessDay = day.Format("2006-01-02")
	return d, nil
}

// billingHistory is the trail of a folio: charges, deposits and payments,
// the billing work and the invoices with their credit notes.
func billingHistory(ctx context.Context, q dbtx.Querier, folio uuid.UUID) ([]BillingHistoryEntry, error) {
	return handle.List[BillingHistoryEntry](q.Query(ctx, `
		SELECT l.posted_at AS at, 'charge_created' AS kind, l.description AS summary, u.full_name AS actor, trim_scale(l.total)::text AS amount, NULL::uuid AS ref
		  FROM billing.folio_lines l LEFT JOIN platform.users u ON u.id = l.posted_by WHERE l.folio_id = $1
		UNION ALL
		SELECT l.voided_at, 'charge_voided', l.description || coalesce(' · ' || l.void_reason, ''), u.full_name, trim_scale(l.total)::text, NULL
		  FROM billing.folio_lines l LEFT JOIN platform.users u ON u.id = l.voided_by WHERE l.folio_id = $1 AND l.voided_at IS NOT NULL
		UNION ALL
		SELECT d.created_at, 'deposit_received', 'Deposit ' || d.number, NULL, trim_scale(d.amount)::text, NULL FROM billing.deposits d WHERE d.folio_id = $1
		UNION ALL
		SELECT d.applied_at, 'deposit_applied', 'Deposit ' || d.number || ' applied', NULL, trim_scale(d.applied_amount)::text, NULL
		  FROM billing.deposits d WHERE d.folio_id = $1 AND d.applied_at IS NOT NULL
		UNION ALL
		SELECT coalesce(p.paid_at, p.created_at), CASE WHEN p.method_type = 'member_account' THEN 'ar_transfer' ELSE 'payment' END,
		  CASE WHEN p.method_type = 'member_account' THEN 'Moved to the AR account · ' || coalesce(p.reference, p.number)
		    ELSE 'Payment ' || p.number || ' · ' || replace(p.method_type, '_', ' ') || ' · ' || p.status END, NULL,
		  trim_scale(p.amount)::text, NULL FROM billing.payments p WHERE p.folio_id = $1 AND p.purpose = 'settlement'
		UNION ALL
		SELECT e.created_at, e.kind, e.summary, e.actor_name, e.detail->>'total', (e.detail->>'invoiceId')::uuid
		  FROM billing.billing_events e WHERE e.folio_id = $1
		UNION ALL
		SELECT i.created_at, 'invoice_created', 'Invoice ' || coalesce(i.number, 'draft') || ' · ' || i.bill_to_name, u.full_name, trim_scale(i.total)::text, i.id
		  FROM billing.invoices i LEFT JOIN platform.users u ON u.id = i.created_by
		  WHERE (i.folio_id = $1 OR i.id IN (SELECT invoice_id FROM billing.folio_lines WHERE folio_id = $1 AND invoice_id IS NOT NULL))
		  -- generated here: the billing event already tells it
		  AND NOT EXISTS (SELECT 1 FROM billing.billing_events e WHERE e.folio_id = $1 AND e.kind = 'invoice_generated' AND e.detail->>'invoiceId' = i.id::text)
		UNION ALL
		SELECT i.issued_at, 'invoice_posted', 'Invoice ' || i.number || ' issued and posted to AR', NULL, trim_scale(i.total)::text, i.id
		  FROM billing.invoices i WHERE i.issued_at IS NOT NULL
		  AND (i.folio_id = $1 OR i.id IN (SELECT invoice_id FROM billing.folio_lines WHERE folio_id = $1 AND invoice_id IS NOT NULL))
		UNION ALL
		SELECT i.sent_at, 'invoice_sent', 'Invoice ' || i.number || ' sent to ' || coalesce(i.bill_to_email, i.bill_to_name), NULL, NULL, i.id
		  FROM billing.invoices i WHERE i.sent_at IS NOT NULL
		  AND (i.folio_id = $1 OR i.id IN (SELECT invoice_id FROM billing.folio_lines WHERE folio_id = $1 AND invoice_id IS NOT NULL))
		UNION ALL
		SELECT i.voided_at, 'invoice_voided', 'Invoice ' || coalesce(i.number, 'draft') || ' voided' || coalesce(' · ' || i.void_reason, ''), NULL,
		  trim_scale(i.total)::text, i.id FROM billing.invoices i WHERE i.voided_at IS NOT NULL
		  AND (i.folio_id = $1 OR i.id IN (SELECT il.invoice_id FROM billing.invoice_lines il JOIN billing.folio_lines fl ON fl.id = il.folio_line_id WHERE fl.folio_id = $1))
		UNION ALL
		SELECT c.created_at, 'credit_note_created', 'Credit note ' || c.number || ' · ' || c.reason, NULL, trim_scale(c.amount)::text, c.invoice_id
		  FROM billing.credit_notes c WHERE c.invoice_id IN (SELECT invoice_id FROM billing.folio_lines WHERE folio_id = $1 AND invoice_id IS NOT NULL)
		ORDER BY at DESC`, folio))
}

// ── commands ──────────────────────────────────────────────────────────────

// billingEvent records a step of the billing work (history and audit).
func billingEvent(ctx context.Context, tx pgx.Tx, property, folio uuid.UUID, kind, summary string, detail map[string]any, reason string) error {
	if detail == nil {
		detail = map[string]any{}
	}
	raw, _ := json.Marshal(detail)
	name := ""
	if p := authz.From(ctx); p != nil {
		name = p.Name
	}
	if _, err := tx.Exec(ctx, `INSERT INTO billing.billing_events (id, property_id, folio_id, kind, summary, detail, actor_id, actor_name)
		VALUES ($1,$2,$3,$4,$5,$6,$7,$8)`, id.New(), property, folio, kind, summary, raw, id.Ptr(actor(ctx)), nullStr(name)); err != nil {
		return err
	}
	return audit.Record(ctx, tx, audit.Entry{Module: "billing", Action: kind, EntityType: "billing.billing_record", EntityID: folio.String(),
		EntityLabel: summary, PropertyID: &property, After: detail, Reason: reason})
}

// ensureRecord opens the billing record of a folio of the property (locked).
func ensureRecord(ctx context.Context, tx pgx.Tx, property, folio uuid.UUID) (string, error) {
	var number, status string
	if err := tx.QueryRow(ctx, `SELECT number, status FROM billing.folios WHERE id = $1 AND property_id = $2`, folio, property).Scan(&number, &status); err != nil {
		if dbtx.IsNoRows(err) {
			return "", errs.NotFound("folio")
		}
		return "", err
	}
	if status == "cancelled" {
		return "", errs.Conflict("folio_cancelled", "the folio is cancelled")
	}
	tag, err := tx.Exec(ctx, `INSERT INTO billing.billing_records (id, property_id, folio_id, created_by, updated_by) VALUES ($1,$2,$3,$4,$4)
		ON CONFLICT (folio_id) DO NOTHING`, id.New(), property, folio, id.Ptr(actor(ctx)))
	if err != nil {
		return "", err
	}
	if tag.RowsAffected() == 1 {
		if err := billingEvent(ctx, tx, property, folio, "billing_opened", "Billing opened for folio "+number, nil, ""); err != nil {
			return "", err
		}
	}
	if _, err := tx.Exec(ctx, `SELECT 1 FROM billing.billing_records WHERE folio_id = $1 FOR UPDATE`, folio); err != nil {
		return "", err
	}
	return number, nil
}

// BillingRecordInput saves Prepare Billing.
type BillingRecordInput struct {
	CustomerID         *uuid.UUID  `json:"customerId,omitempty" doc:"Bill to another customer than the folio's"`
	CorporateAccountID *uuid.UUID  `json:"corporateAccountId,omitempty" doc:"Bill to the company"`
	BillToName         string      `json:"billToName,omitempty"`
	BillToAddress      string      `json:"billToAddress,omitempty"`
	BillToNPWP         string      `json:"billToNpwp,omitempty"`
	BillToEmail        string      `json:"billToEmail,omitempty"`
	BillToPhone        string      `json:"billToPhone,omitempty"`
	TermsDays          *int        `json:"termsDays,omitempty" doc:"null: Credit Policies default"`
	CustomerPO         string      `json:"customerPo,omitempty"`
	ContractRef        string      `json:"contractRef,omitempty"`
	BillingRef         string      `json:"billingRef,omitempty"`
	Notes              string      `json:"notes,omitempty"`
	InternalNotes      string      `json:"internalNotes,omitempty"`
	AttachmentFileIDs  []uuid.UUID `json:"attachmentFileIds,omitempty"`
}

// SaveBillingRecord saves Prepare Billing (FR: Save Billing).
func SaveBillingRecord(ctx context.Context, tx pgx.Tx, property, folio uuid.UUID, in BillingRecordInput) (BillingRecordDetail, error) {
	if in.TermsDays != nil && *in.TermsDays < 0 {
		return BillingRecordDetail{}, handle.Invalid("termsDays", "invalid", "zero or more days")
	}
	if in.CorporateAccountID != nil {
		var ok bool
		if err := tx.QueryRow(ctx, `SELECT EXISTS (SELECT 1 FROM crm.corporate_accounts WHERE id = $1 AND property_id = $2)`, *in.CorporateAccountID, property).
			Scan(&ok); err != nil || !ok {
			return BillingRecordDetail{}, handle.Invalid("corporateAccountId", "not_found", "not in this property")
		}
	}
	if in.CustomerID != nil {
		var ok bool
		if err := tx.QueryRow(ctx, `SELECT EXISTS (SELECT 1 FROM crm.customers WHERE id = $1 AND property_id = $2)`, *in.CustomerID, property).
			Scan(&ok); err != nil || !ok {
			return BillingRecordDetail{}, handle.Invalid("customerId", "not_found", "not in this property")
		}
	}
	files, err := invoiceFiles(ctx, tx, in.AttachmentFileIDs)
	if err != nil {
		return BillingRecordDetail{}, err
	}
	number, err := ensureRecord(ctx, tx, property, folio)
	if err != nil {
		return BillingRecordDetail{}, err
	}
	rows, err := tx.Query(ctx, `SELECT customer_id, corporate_account_id, bill_to_name, bill_to_address, bill_to_npwp, bill_to_email,
		bill_to_phone, terms_days, customer_po, contract_ref, billing_ref, notes, internal_notes, attachment_file_ids, version
		FROM billing.billing_records WHERE folio_id = $1`, folio)
	before, err := handle.One[BillingRecord](rows, err, "billing record")
	if err != nil {
		return BillingRecordDetail{}, err
	}
	if _, err := tx.Exec(ctx, `UPDATE billing.billing_records SET customer_id = $2, corporate_account_id = $3, bill_to_name = $4, bill_to_address = $5,
		bill_to_npwp = $6, bill_to_email = $7, bill_to_phone = $8, terms_days = $9, customer_po = $10, contract_ref = $11, billing_ref = $12, notes = $13,
		internal_notes = $14, attachment_file_ids = $15, version = version + 1, updated_by = $16 WHERE folio_id = $1`,
		folio, in.CustomerID, in.CorporateAccountID, nullStr(strings.TrimSpace(in.BillToName)), nullStr(strings.TrimSpace(in.BillToAddress)),
		nullStr(strings.TrimSpace(in.BillToNPWP)), nullStr(strings.TrimSpace(in.BillToEmail)), nullStr(strings.TrimSpace(in.BillToPhone)), in.TermsDays,
		nullStr(strings.TrimSpace(in.CustomerPO)), nullStr(strings.TrimSpace(in.ContractRef)), nullStr(strings.TrimSpace(in.BillingRef)),
		nullStr(strings.TrimSpace(in.Notes)), nullStr(strings.TrimSpace(in.InternalNotes)), files, id.Ptr(actor(ctx))); err != nil {
		return BillingRecordDetail{}, err
	}
	changed := []string{}
	cmp := func(field string, a, b any) {
		ja, _ := json.Marshal(a)
		jb, _ := json.Marshal(b)
		if string(ja) != string(jb) {
			changed = append(changed, field)
		}
	}
	nz := func(s string) *string { return nullStr(strings.TrimSpace(s)) }
	cmp("bill to customer", before.CustomerID, in.CustomerID)
	cmp("bill to company", before.CorporateAccountID, in.CorporateAccountID)
	cmp("bill-to name", before.BillToName, nz(in.BillToName))
	cmp("billing address", before.BillToAddress, nz(in.BillToAddress))
	cmp("NPWP", before.BillToNPWP, nz(in.BillToNPWP))
	cmp("e-mail", before.BillToEmail, nz(in.BillToEmail))
	cmp("payment term", before.TermsDays, in.TermsDays)
	cmp("references", []any{before.CustomerPO, before.ContractRef, before.BillingRef}, []any{nz(in.CustomerPO), nz(in.ContractRef), nz(in.BillingRef)})
	cmp("notes", []any{before.Notes, before.InternalNotes}, []any{nz(in.Notes), nz(in.InternalNotes)})
	cmp("documents", before.AttachmentFileIDs, files)
	if len(changed) > 0 {
		if err := billingEvent(ctx, tx, property, folio, "billing_edited", "Billing edited: "+strings.Join(changed, ", "),
			map[string]any{"folio": number, "changed": changed}, ""); err != nil {
			return BillingRecordDetail{}, err
		}
	}
	return GetBillingRecord(ctx, tx, property, folio)
}

// MarkReady marks a folio ready to invoice once every validation passed.
func MarkReady(ctx context.Context, tx pgx.Tx, property, folio uuid.UUID) (BillingRecordDetail, error) {
	number, err := ensureRecord(ctx, tx, property, folio)
	if err != nil {
		return BillingRecordDetail{}, err
	}
	it, err := BillingItemOf(ctx, tx, property, folio)
	if err != nil {
		return BillingRecordDetail{}, err
	}
	if it.Status == BillInvoiced || it.Status == BillSettled {
		return BillingRecordDetail{}, errs.Conflict("nothing_to_bill", "the folio has nothing left to bill")
	}
	if it.Blocking > 0 {
		return BillingRecordDetail{}, errs.Conflict("billing_exceptions", "resolve the blocking exceptions first: "+exceptionList(it))
	}
	if _, err := tx.Exec(ctx, `UPDATE billing.billing_records SET status = 'ready', ready_at = now(), ready_by = $2, version = version + 1, updated_by = $2
		WHERE folio_id = $1`, folio, id.Ptr(actor(ctx))); err != nil {
		return BillingRecordDetail{}, err
	}
	if err := billingEvent(ctx, tx, property, folio, "billing_marked_ready", "Billing marked ready to invoice",
		map[string]any{"folio": number, "toInvoice": it.ToInvoice}, ""); err != nil {
		return BillingRecordDetail{}, err
	}
	return GetBillingRecord(ctx, tx, property, folio)
}

// errKind is the kind of an application error ("" for any other error).
func errKind(err error) errs.Kind {
	var e *errs.Error
	if errors.As(err, &e) {
		return e.Kind
	}
	return ""
}

func exceptionList(it BillingItem) string {
	var out []string
	for _, e := range it.Exceptions {
		if e.Resolved == nil {
			out = append(out, e.Label)
		}
	}
	return strings.Join(out, ", ")
}

// ApproveBilling approves the amount to invoice and the adjustments of a
// folio (Finance Manager; General Manager / Director from the executive
// threshold).
func ApproveBilling(ctx context.Context, tx pgx.Tx, property, folio uuid.UUID, reason string) (BillingRecordDetail, error) {
	number, err := ensureRecord(ctx, tx, property, folio)
	if err != nil {
		return BillingRecordDetail{}, err
	}
	it, err := BillingItemOf(ctx, tx, property, folio)
	if err != nil {
		return BillingRecordDetail{}, err
	}
	bc, err := newBillingContext(ctx, tx, property)
	if err != nil {
		return BillingRecordDetail{}, err
	}
	if bc.approvalLevel(dec(it.ToInvoice)) == "executive" {
		if err := authz.RequireAt(ctx, PermBillingApproveExecutive, property); err != nil {
			return BillingRecordDetail{}, errs.Forbidden("billing of this value is approved by the General Manager / Director")
		}
	}
	if _, err := tx.Exec(ctx, `UPDATE billing.billing_records SET approved_amount = $2::numeric, approved_at = now(), approved_by = $3, version = version + 1,
		updated_by = $3 WHERE folio_id = $1`, folio, it.ToInvoice, id.Ptr(actor(ctx))); err != nil {
		return BillingRecordDetail{}, err
	}
	tag, err := tx.Exec(ctx, `UPDATE billing.billing_adjustments SET approved_at = now(), approved_by = $2 WHERE folio_id = $1 AND approved_at IS NULL`,
		folio, id.Ptr(actor(ctx)))
	if err != nil {
		return BillingRecordDetail{}, err
	}
	summary := "Billing approved for " + it.ToInvoice
	if n := tag.RowsAffected(); n > 0 {
		summary += fmt.Sprintf(" with %d adjustment(s)", n)
	}
	if err := billingEvent(ctx, tx, property, folio, "billing_approved", summary,
		map[string]any{"folio": number, "amount": it.ToInvoice, "adjustments": tag.RowsAffected()}, reason); err != nil {
		return BillingRecordDetail{}, err
	}
	return GetBillingRecord(ctx, tx, property, folio)
}

// ResolveException acknowledges (accountant) or overrides (Finance Manager)
// an exception with a reason.
func ResolveException(ctx context.Context, tx pgx.Tx, property, folio uuid.UUID, code, reason string) (BillingRecordDetail, error) {
	if err := handle.Required("reason", reason); err != nil {
		return BillingRecordDetail{}, err
	}
	if _, err := ensureRecord(ctx, tx, property, folio); err != nil {
		return BillingRecordDetail{}, err
	}
	it, err := BillingItemOf(ctx, tx, property, folio)
	if err != nil {
		return BillingRecordDetail{}, err
	}
	var ex *BillingException
	for i := range it.Exceptions {
		if it.Exceptions[i].Code == code {
			ex = &it.Exceptions[i]
		}
	}
	if ex == nil {
		return BillingRecordDetail{}, errs.Conflict("exception_not_found", "the folio has no such exception (already fixed?)")
	}
	switch ex.Resolution {
	case "fix":
		return BillingRecordDetail{}, errs.Conflict("fix_required", ex.Message+": correct the data in Prepare Billing")
	case "approve":
		return ApproveBilling(ctx, tx, property, folio, reason)
	case "override":
		if err := authz.RequireAt(ctx, PermBillingApprove, property); err != nil {
			return BillingRecordDetail{}, errs.Forbidden("only the Finance Manager can override " + ex.Label)
		}
	}
	name := ""
	if p := authz.From(ctx); p != nil {
		name = p.Name
	}
	res, _ := json.Marshal(BillingResolution{Reason: reason, By: actor(ctx), ByName: name, At: time.Now().UTC()})
	if _, err := tx.Exec(ctx, `UPDATE billing.billing_records SET resolved = resolved || jsonb_build_object($2::text, $3::jsonb), version = version + 1,
		updated_by = $4 WHERE folio_id = $1`, folio, code, res, id.Ptr(actor(ctx))); err != nil {
		return BillingRecordDetail{}, err
	}
	verb := "acknowledged"
	if ex.Resolution == "override" {
		verb = "overridden"
	}
	if err := billingEvent(ctx, tx, property, folio, "exception_resolved", ex.Label+" "+verb+": "+reason,
		map[string]any{"code": code, "resolution": ex.Resolution}, reason); err != nil {
		return BillingRecordDetail{}, err
	}
	return GetBillingRecord(ctx, tx, property, folio)
}

// ── adjustments ───────────────────────────────────────────────────────────

// BillingAdjustmentInput changes a charge before it is invoiced.
type BillingAdjustmentInput struct {
	LineID           uuid.UUID `json:"lineId"`
	Kind             string    `json:"kind" enum:"quantity,price,discount,service_charge,tax,revenue_allocation"`
	Quantity         string    `json:"quantity,omitempty" doc:"quantity: the new quantity"`
	UnitPrice        string    `json:"unitPrice,omitempty" doc:"price: the new unit price"`
	Amount           string    `json:"amount,omitempty" doc:"discount: the discount before tax; service_charge / tax: the new amount of the charge"`
	BusinessLine     string    `json:"businessLine,omitempty" doc:"revenue_allocation: the new business line"`
	RevenueComponent string    `json:"revenueComponent,omitempty" doc:"revenue_allocation: the new revenue component"`
	Reason           string    `json:"reason"`
	Reference        string    `json:"reference,omitempty" doc:"Supporting reference (approval memo, complaint, PO …)"`
}

type adjLine struct {
	ID, FolioID, Property         uuid.UUID
	ChargeType, Desc, Line, Comp  string
	Qty, Unit, Net, Svc, Tax, Tot decimal.Decimal
	Liability                     bool
	BenType                       *string
	BenID, Snapshot, Invoice      *uuid.UUID
	Currency, FolioStatus         string
	TaxLines                      []byte
}

// AdjustBilling posts a correcting line for a change of quantity, price,
// discount, service charge, tax or revenue allocation. The original line is
// never changed; the adjustment keeps the previous and the new value.
// Adjustments by an accountant wait for the Finance Manager's approval.
func (s *Service) AdjustBilling(ctx context.Context, tx pgx.Tx, property, folio uuid.UUID, in BillingAdjustmentInput) (BillingRecordDetail, error) {
	if err := handle.Required("reason", in.Reason); err != nil {
		return BillingRecordDetail{}, err
	}
	if _, err := ensureRecord(ctx, tx, property, folio); err != nil {
		return BillingRecordDetail{}, err
	}
	var l adjLine
	var qty, unit, net, svc, tax, tot string
	err := tx.QueryRow(ctx, `SELECT l.id, l.folio_id, l.property_id, l.charge_type, l.description, l.business_line, coalesce(l.revenue_component, l.charge_type),
		l.quantity::text, l.unit_price::text, l.net_amount::text, l.service_amount::text, l.tax_amount::text, l.total::text, l.liability, l.beneficiary_type,
		l.beneficiary_id, l.pricing_snapshot_id, l.invoice_id, f.currency, f.status, l.tax_lines
		FROM billing.folio_lines l JOIN billing.folios f ON f.id = l.folio_id
		WHERE l.id = $1 AND l.folio_id = $2 AND l.voided_at IS NULL FOR UPDATE OF l, f`, in.LineID, folio).
		Scan(&l.ID, &l.FolioID, &l.Property, &l.ChargeType, &l.Desc, &l.Line, &l.Comp, &qty, &unit, &net, &svc, &tax, &tot, &l.Liability, &l.BenType,
			&l.BenID, &l.Snapshot, &l.Invoice, &l.Currency, &l.FolioStatus, &l.TaxLines)
	if dbtx.IsNoRows(err) {
		return BillingRecordDetail{}, errs.Validation("invalid_line", "charge not found on this folio", errs.Field("lineId", "not_found", "not on the folio"))
	}
	if err != nil {
		return BillingRecordDetail{}, err
	}
	if l.Invoice != nil {
		return BillingRecordDetail{}, errs.Conflict("line_invoiced", "the charge is invoiced; issue a credit note on the invoice instead")
	}
	if l.FolioStatus != "open" {
		return BillingRecordDetail{}, ErrFolioClosed // a closed folio is settled; a cancelled one has nothing to bill
	}
	l.Qty, l.Unit, l.Net, l.Svc, l.Tax, l.Tot = dec(qty), dec(unit), dec(net), dec(svc), dec(tax), dec(tot)
	// current values: the line with the adjustments already made to it
	var curNet, curSvc, curTax string
	if err := tx.QueryRow(ctx, `SELECT coalesce(sum(net_amount), 0)::text, coalesce(sum(service_amount), 0)::text, coalesce(sum(tax_amount), 0)::text
		FROM billing.folio_lines WHERE voided_at IS NULL AND (id = $1 OR (reference_type = 'billing.adjustment' AND reference_id = $1))`, l.ID).
		Scan(&curNet, &curSvc, &curTax); err != nil {
		return BillingRecordDetail{}, err
	}
	last := func(kind, def string) (string, error) {
		var v string
		err := tx.QueryRow(ctx, `SELECT new_value FROM billing.billing_adjustments WHERE folio_line_id = $1 AND kind = $2 ORDER BY created_at DESC LIMIT 1`,
			l.ID, kind).Scan(&v)
		if dbtx.IsNoRows(err) {
			return def, nil
		}
		return v, err
	}
	pl := places(l.Currency)
	r := func(d decimal.Decimal) decimal.Decimal { return d.Round(pl) }
	type delta struct {
		net, svc, tax  decimal.Decimal
		line, comp     string
		desc, chargeTy string
	}
	var (
		deltas   []delta
		prev, nv string
	)
	// a change of quantity × unit price splits like the line: on the net
	// amount, or on the all-in total when the unit price includes tax
	part := func(d decimal.Decimal) delta { return delta{net: r(d)} }
	if !l.Net.IsZero() {
		svcRate, taxRate := l.Svc.Div(l.Net), l.Tax.Div(l.Net)
		part = func(d decimal.Decimal) delta { return delta{net: r(d), svc: r(d.Mul(svcRate)), tax: r(d.Mul(taxRate))} }
		if l.Qty.Mul(l.Unit).Sub(l.Net).Abs().GreaterThan(decimal.NewFromInt(1)) && l.Qty.Mul(l.Unit).Sub(l.Tot).Abs().LessThanOrEqual(decimal.NewFromInt(1)) &&
			!l.Tot.IsZero() {
			netShare := l.Net.Div(l.Tot)
			part = func(d decimal.Decimal) delta {
				n := r(d.Mul(netShare))
				return delta{net: n, svc: r(n.Mul(svcRate)), tax: r(d.Sub(n).Sub(r(n.Mul(svcRate))))}
			}
		}
	}
	curQty, curUnit := l.Qty, l.Unit
	if v, err := last("quantity", l.Qty.String()); err != nil {
		return BillingRecordDetail{}, err
	} else {
		curQty = dec(v)
	}
	if v, err := last("price", l.Unit.String()); err != nil {
		return BillingRecordDetail{}, err
	} else {
		curUnit = dec(v)
	}
	label := strings.ReplaceAll(in.Kind, "_", " ")
	switch in.Kind {
	case "quantity", "price":
		if l.ChargeType == "discount" {
			return BillingRecordDetail{}, errs.Conflict("not_adjustable", "a discount line is changed by another discount")
		}
		newQty, newUnit := curQty, curUnit
		if in.Kind == "quantity" {
			q, err := handle.Decimal("quantity", in.Quantity, decimal.Zero)
			if err != nil || !q.IsPositive() {
				return BillingRecordDetail{}, handle.Invalid("quantity", "invalid", "a quantity above zero")
			}
			newQty, prev, nv = q, curQty.String(), q.String()
		} else {
			p, err := handle.Decimal("unitPrice", in.UnitPrice, decimal.NewFromInt(-1))
			if err != nil || p.IsNegative() {
				return BillingRecordDetail{}, handle.Invalid("unitPrice", "invalid", "zero or more")
			}
			newUnit, prev, nv = p, curUnit.String(), p.String()
		}
		if prev == nv {
			return BillingRecordDetail{}, errs.Conflict("no_change", "the value is unchanged")
		}
		d := part(newQty.Mul(newUnit).Sub(curQty.Mul(curUnit)))
		d.desc = fmt.Sprintf("Adjustment %s %s → %s · %s", label, prev, nv, l.Desc)
		deltas = append(deltas, d)
	case "discount":
		a, err := handle.Decimal("amount", in.Amount, decimal.Zero)
		if err != nil || !a.IsPositive() {
			return BillingRecordDetail{}, handle.Invalid("amount", "invalid", "a discount above zero")
		}
		cn := dec(curNet)
		if a.GreaterThan(cn) {
			return BillingRecordDetail{}, handle.Invalid("amount", "too_high", "at most the net amount of the charge ("+cn.StringFixed(pl)+")")
		}
		var given string
		if err := tx.QueryRow(ctx, `SELECT coalesce(sum(-net_amount), 0)::text FROM billing.folio_lines WHERE voided_at IS NULL AND reference_type = 'billing.adjustment'
			AND reference_id = $1 AND charge_type = 'discount'`, l.ID).Scan(&given); err != nil {
			return BillingRecordDetail{}, err
		}
		ratio := a.Div(cn)
		d := delta{net: r(a.Neg()), svc: r(dec(curSvc).Mul(ratio).Neg()), tax: r(dec(curTax).Mul(ratio).Neg()), chargeTy: "discount"}
		prev, nv = dec(given).StringFixed(pl), dec(given).Add(a).StringFixed(pl)
		d.desc = "Discount · " + l.Desc
		deltas = append(deltas, d)
	case "service_charge", "tax":
		a, err := handle.Decimal("amount", in.Amount, decimal.NewFromInt(-1))
		if err != nil || a.IsNegative() {
			return BillingRecordDetail{}, handle.Invalid("amount", "invalid", "zero or more")
		}
		cur := dec(curSvc)
		if in.Kind == "tax" {
			cur = dec(curTax)
		}
		if a.Equal(cur) {
			return BillingRecordDetail{}, errs.Conflict("no_change", "the value is unchanged")
		}
		d := delta{svc: a.Sub(cur)}
		if in.Kind == "tax" {
			d = delta{tax: a.Sub(cur)}
		}
		prev, nv = cur.StringFixed(pl), a.StringFixed(pl)
		d.desc = fmt.Sprintf("Adjustment %s %s → %s · %s", label, prev, nv, l.Desc)
		deltas = append(deltas, d)
	case "revenue_allocation":
		if !slices.Contains(BusinessLines, in.BusinessLine) {
			return BillingRecordDetail{}, handle.Invalid("businessLine", "invalid", "unknown business line")
		}
		if !slices.Contains(RevenueComponents, in.RevenueComponent) && !slices.Contains(chargeTypes, in.RevenueComponent) {
			return BillingRecordDetail{}, handle.Invalid("revenueComponent", "invalid", "unknown revenue component")
		}
		curAlloc, err := last("revenue_allocation", l.Line+"/"+l.Comp)
		if err != nil {
			return BillingRecordDetail{}, err
		}
		nv = in.BusinessLine + "/" + in.RevenueComponent
		if nv == curAlloc {
			return BillingRecordDetail{}, errs.Conflict("no_change", "the allocation is unchanged")
		}
		cl, cc, _ := strings.Cut(curAlloc, "/")
		var an, as, at string
		if err := tx.QueryRow(ctx, `SELECT coalesce(sum(net_amount), 0)::text, coalesce(sum(service_amount), 0)::text, coalesce(sum(tax_amount), 0)::text
			FROM billing.folio_lines WHERE voided_at IS NULL AND (id = $1 OR (reference_type = 'billing.adjustment' AND reference_id = $1))
			AND business_line = $2 AND coalesce(revenue_component, charge_type) = $3`, l.ID, cl, cc).Scan(&an, &as, &at); err != nil {
			return BillingRecordDetail{}, err
		}
		prev = curAlloc
		deltas = append(deltas,
			delta{net: dec(an).Neg(), svc: dec(as).Neg(), tax: dec(at).Neg(), line: cl, comp: cc, desc: "Revenue moved to " + nv + " · " + l.Desc},
			delta{net: dec(an), svc: dec(as), tax: dec(at), line: in.BusinessLine, comp: in.RevenueComponent, desc: "Revenue moved from " + prev + " · " + l.Desc})
	default:
		return BillingRecordDetail{}, handle.Invalid("kind", "invalid", "quantity, price, discount, service_charge, tax or revenue_allocation")
	}
	amount := decimal.Zero
	posted := []uuid.UUID{}
	for _, d := range deltas {
		if d.line == "" {
			d.line, d.comp = l.Line, l.Comp
		}
		if d.chargeTy == "" {
			d.chargeTy = l.ChargeType
			if in.Kind == "revenue_allocation" {
				d.chargeTy = "other"
				if slices.Contains(chargeTypes, d.comp) {
					d.chargeTy = d.comp
				}
			}
		}
		lid, err := postAdjustmentLine(ctx, tx, l, d.chargeTy, d.desc, d.line, d.comp, d.net, d.svc, d.tax)
		if err != nil {
			return BillingRecordDetail{}, err
		}
		posted = append(posted, lid)
		amount = amount.Add(d.net).Add(d.svc).Add(d.tax)
	}
	approved := authz.From(ctx) != nil && authz.From(ctx).Can(PermBillingApprove, &property)
	var approvedAt *time.Time
	if approved {
		now := time.Now().UTC()
		approvedAt = &now
	}
	if _, err := tx.Exec(ctx, `INSERT INTO billing.billing_adjustments (id, property_id, folio_id, folio_line_id, kind, previous_value, new_value, amount,
		posted_line_ids, reason, reference, approved_at, approved_by, created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8::numeric,$9,$10,$11,$12,$13,$14)`,
		id.New(), property, folio, l.ID, in.Kind, prev, nv, amount.String(), posted, in.Reason, nullStr(strings.TrimSpace(in.Reference)), approvedAt,
		func() *uuid.UUID {
			if approved {
				return id.Ptr(actor(ctx))
			}
			return nil
		}(), id.Ptr(actor(ctx))); err != nil {
		return BillingRecordDetail{}, err
	}
	kind := map[string]string{"discount": "discount_changed", "tax": "tax_changed"}[in.Kind]
	if kind == "" {
		kind = "billing_adjusted"
	}
	if err := billingEvent(ctx, tx, property, folio, kind, fmt.Sprintf("%s of %s: %s → %s (%s)", strings.ToUpper(label[:1])+label[1:], l.Desc, prev, nv,
		amount.StringFixed(pl)), map[string]any{"lineId": l.ID, "kind": in.Kind, "previous": prev, "new": nv, "amount": amount.String(),
		"reference": in.Reference, "approved": approved}, in.Reason); err != nil {
		return BillingRecordDetail{}, err
	}
	return GetBillingRecord(ctx, tx, property, folio)
}

// postAdjustmentLine posts a correcting line on the (locked, open) folio: it
// references the adjusted line and keeps its pricing snapshot, liability, tax
// lines and beneficiary.
func postAdjustmentLine(ctx context.Context, tx pgx.Tx, src adjLine, chargeType, desc, line, comp string, net, svc, tax decimal.Decimal) (uuid.UUID, error) {
	total := net.Add(svc).Add(tax)
	comps, _ := json.Marshal([]map[string]any{{"code": comp, "name": strings.ReplaceAll(comp, "_", " "), "amount": net.String(), "liability": src.Liability}})
	lid := id.New()
	taxes := src.TaxLines
	if taxes == nil {
		taxes = []byte("[]")
	}
	if _, err := tx.Exec(ctx, `INSERT INTO billing.folio_lines (id, property_id, folio_id, charge_type, description, quantity, unit_price, net_amount,
		tax_amount, service_amount, total, currency, components, pricing_snapshot_id, reference_type, reference_id, liability, posted_by, business_line,
		revenue_component, tax_lines, beneficiary_type, beneficiary_id)
		VALUES ($1,$2,$3,$4,$5,1,$6::numeric,$6::numeric,$7::numeric,$8::numeric,$9::numeric,$10,$11,$12,'billing.adjustment',$13,$14,$15,$16,$17,$18,$19,$20)`,
		lid, src.Property, src.FolioID, chargeType, desc, net.String(), tax.String(), svc.String(), total.String(), src.Currency, comps, src.Snapshot, src.ID,
		src.Liability, id.Ptr(actor(ctx)), line, comp, taxes, src.BenType, src.BenID); err != nil {
		return uuid.Nil, err
	}
	_, err := tx.Exec(ctx, `UPDATE billing.folios SET version = version + 1, updated_by = $2 WHERE id = $1`, src.FolioID, id.Ptr(actor(ctx)))
	return lid, err
}

// ── generation ────────────────────────────────────────────────────────────

// BillingGenerateInput generates the invoices of folios.
type BillingGenerateInput struct {
	FolioIDs []uuid.UUID `json:"folioIds"`
	Send     bool        `json:"send,omitempty" doc:"Send each invoice to the customer (e-mail / WhatsApp / in-app) once issued"`
}

// BillingGenerateResult is the outcome per folio.
type BillingGenerateResult struct {
	FolioID       uuid.UUID  `json:"folioId"`
	Number        string     `json:"number"`
	InvoiceID     *uuid.UUID `json:"invoiceId,omitempty"`
	InvoiceNumber *string    `json:"invoiceNumber,omitempty"`
	Total         string     `json:"total,omitempty"`
	Sent          bool       `json:"sent"`
	Error         string     `json:"error,omitempty" doc:"Why no invoice was generated"`
}

// BillingGenerateResults sums a batch.
type BillingGenerateResults struct {
	Generated int                     `json:"generated"`
	Skipped   int                     `json:"skipped"`
	Results   []BillingGenerateResult `json:"results"`
}

// invoiceInputOf builds the invoice request of a prepared folio.
func invoiceInputOf(ctx context.Context, q dbtx.Querier, folio uuid.UUID) (InvoiceInput, error) {
	in := InvoiceInput{FolioID: &folio, Issue: true}
	recs, err := handle.List[BillingRecord](q.Query(ctx, `SELECT customer_id, corporate_account_id, bill_to_name, bill_to_address, bill_to_npwp, bill_to_email,
		bill_to_phone, terms_days, customer_po, contract_ref, billing_ref, notes, internal_notes, attachment_file_ids FROM billing.billing_records
		WHERE folio_id = $1`, folio))
	if err != nil || len(recs) == 0 {
		return in, err
	}
	r := recs[0]
	in.CustomerID, in.CorporateAccountID, in.TermsDays = r.CustomerID, r.CorporateAccountID, r.TermsDays
	in.BillTo = &BillTo{Name: deref(r.BillToName), Address: deref(r.BillToAddress), NPWP: deref(r.BillToNPWP), Email: deref(r.BillToEmail), Phone: deref(r.BillToPhone)}
	in.CustomerPO, in.ContractRef, in.BillingRef = deref(r.CustomerPO), deref(r.ContractRef), deref(r.BillingRef)
	in.Notes, in.InternalNotes, in.AttachmentFileIDs = deref(r.Notes), deref(r.InternalNotes), r.AttachmentFileIDs
	return in, nil
}

// issueAndSend creates, issues and (optionally) sends one invoice inside a
// savepoint, so one failing folio does not stop the batch.
func (h *HTTP) issueAndSend(ctx context.Context, tx pgx.Tx, property uuid.UUID, in InvoiceInput, send bool, folios []uuid.UUID, summary string) (InvoiceDetail, bool, error) {
	sp, err := tx.Begin(ctx)
	if err != nil {
		return InvoiceDetail{}, false, err
	}
	d, err := h.CreateInvoice(ctx, sp, property, in)
	sent := false
	if err == nil && send {
		if err = h.sendInvoice(ctx, sp, property, d.Invoice, "billing.invoice", nil); err == nil {
			if _, err = sp.Exec(ctx, `UPDATE billing.invoices SET sent_at = now() WHERE id = $1`, d.ID); err == nil {
				sent = true
				err = audit.Record(ctx, sp, audit.Entry{Module: "billing", Action: "send", EntityType: "billing.invoice", EntityID: d.ID.String(),
					EntityLabel: deref(d.Number), PropertyID: &property})
			}
		}
	}
	if err == nil {
		for _, f := range folios {
			if err = billingEvent(ctx, sp, property, f, "invoice_generated", fmt.Sprintf(summary, deref(d.Number)),
				map[string]any{"invoiceId": d.ID, "number": d.Number, "total": d.Total, "sent": sent}, ""); err != nil {
				break
			}
		}
	}
	if err != nil {
		_ = sp.Rollback(ctx)
		return InvoiceDetail{}, false, err
	}
	return d, sent, sp.Commit(ctx)
}

// GenerateInvoices generates one invoice per folio for the folios without a
// blocking exception; the others are skipped with the reason.
func (h *HTTP) GenerateInvoices(ctx context.Context, tx pgx.Tx, property uuid.UUID, in BillingGenerateInput) (BillingGenerateResults, error) {
	if len(in.FolioIDs) == 0 {
		return BillingGenerateResults{}, handle.Invalid("folioIds", "required", "choose the folios to invoice")
	}
	if len(in.FolioIDs) > 200 {
		return BillingGenerateResults{}, handle.Invalid("folioIds", "too_many", "at most 200 folios at once")
	}
	if err := authz.RequireAt(ctx, "billing.invoice.issue", property); err != nil {
		return BillingGenerateResults{}, err
	}
	out := BillingGenerateResults{Results: []BillingGenerateResult{}}
	seen := map[uuid.UUID]bool{}
	for _, fid := range in.FolioIDs {
		if seen[fid] {
			continue
		}
		seen[fid] = true
		it, err := BillingItemOf(ctx, tx, property, fid)
		if err != nil {
			if errKind(err) == errs.KindNotFound {
				out.Results = append(out.Results, BillingGenerateResult{FolioID: fid, Error: "folio not found"})
				out.Skipped++
				if err := audit.Record(ctx, tx, audit.Entry{Module: "billing", Action: "invoice_skipped", EntityType: "billing.billing_record",
					EntityID: fid.String(), PropertyID: &property, Reason: "folio not found"}); err != nil {
					return out, err
				}
				continue
			}
			return out, err
		}
		res := BillingGenerateResult{FolioID: fid, Number: it.Number}
		switch {
		case it.Status == BillInvoiced || it.Status == BillSettled || it.Status == BillCancelled:
			res.Error = "nothing to invoice (" + strings.ReplaceAll(it.Status, "_", " ") + ")"
		case !it.CanInvoice:
			res.Error = "requires attention: " + exceptionList(it)
		}
		if res.Error == "" {
			req, err := invoiceInputOf(ctx, tx, fid)
			if err != nil {
				return out, err
			}
			d, sent, err := h.issueAndSend(ctx, tx, property, req, in.Send, []uuid.UUID{fid}, "Invoice %s generated")
			if err != nil {
				if errKind(err) == "" || errKind(err) == errs.KindInternal {
					return out, err
				}
				res.Error = err.Error()
			} else {
				res.InvoiceID, res.InvoiceNumber, res.Total, res.Sent = &d.ID, d.Number, d.Total, sent
			}
		}
		if res.Error != "" {
			out.Skipped++
			if err := audit.Record(ctx, tx, audit.Entry{Module: "billing", Action: "invoice_skipped", EntityType: "billing.billing_record", EntityID: fid.String(),
				EntityLabel: it.Number, PropertyID: &property, Reason: res.Error}); err != nil {
				return out, err
			}
		} else {
			out.Generated++
		}
		out.Results = append(out.Results, res)
	}
	return out, nil
}

// ConsolidateInput combines folios of one payer into one invoice.
type ConsolidateInput struct {
	FolioIDs  []uuid.UUID `json:"folioIds"`
	TermsDays *int        `json:"termsDays,omitempty" doc:"Default: the first folio's billing, or Credit Policies"`
	Send      bool        `json:"send,omitempty"`
}

// ConsolidateBilling generates one invoice for several folios of the same
// payer, each invoice line linked to its source folio charge (Finance
// Manager approves consolidated billing).
func (h *HTTP) ConsolidateBilling(ctx context.Context, tx pgx.Tx, property uuid.UUID, in ConsolidateInput) (BillingGenerateResult, error) {
	ids := []uuid.UUID{}
	for _, x := range in.FolioIDs {
		if !slices.Contains(ids, x) {
			ids = append(ids, x)
		}
	}
	if len(ids) < 2 {
		return BillingGenerateResult{}, handle.Invalid("folioIds", "too_few", "choose at least two folios")
	}
	if err := authz.RequireAt(ctx, "billing.invoice.issue", property); err != nil {
		return BillingGenerateResult{}, err
	}
	var payer string
	var customer, company *uuid.UUID
	numbers := []string{}
	for _, fid := range ids {
		it, err := BillingItemOf(ctx, tx, property, fid)
		if err != nil {
			return BillingGenerateResult{}, err
		}
		if it.Status == BillInvoiced || it.Status == BillSettled || it.Status == BillCancelled {
			return BillingGenerateResult{}, errs.Conflict("nothing_to_invoice", it.Number+" has nothing to invoice")
		}
		// approval of each folio is replaced by the approval of the consolidation
		blocking := []string{}
		for _, e := range it.Exceptions {
			if e.Resolved == nil && e.Code != "approval_required" {
				blocking = append(blocking, e.Label)
			}
		}
		if len(blocking) > 0 {
			return BillingGenerateResult{}, errs.Conflict("billing_exceptions", it.Number+" requires attention: "+strings.Join(blocking, ", "))
		}
		key := "none"
		switch it.BillToKind {
		case "company":
			key = "company:" + it.CorporateAccountID.String()
		case "customer":
			key = "customer:" + it.CustomerID.String()
		}
		if payer == "" {
			payer, customer, company = key, it.CustomerID, it.CorporateAccountID
		} else if payer != key {
			return BillingGenerateResult{}, errs.Conflict("payer_mismatch", "every folio of a consolidated invoice must be billed to the same company or customer ("+it.Number+" differs)")
		}
		numbers = append(numbers, it.Number)
	}
	req, err := invoiceInputOf(ctx, tx, ids[0])
	if err != nil {
		return BillingGenerateResult{}, err
	}
	req.FolioID, req.FolioIDs, req.CustomerID, req.CorporateAccountID = nil, ids, customer, company
	if in.TermsDays != nil {
		req.TermsDays = in.TermsDays
	}
	if req.BillingRef == "" {
		req.BillingRef = strings.Join(numbers, ", ")
	}
	d, sent, err := h.issueAndSend(ctx, tx, property, req, in.Send, ids, "Consolidated invoice %s generated ("+strings.Join(numbers, ", ")+")")
	if err != nil {
		return BillingGenerateResult{}, err
	}
	return BillingGenerateResult{FolioID: ids[0], Number: strings.Join(numbers, ", "), InvoiceID: &d.ID, InvoiceNumber: d.Number, Total: d.Total, Sent: sent}, nil
}

// BillingSplitInput splits a folio across billing parties.
type BillingSplitInput struct {
	CustomerID         *uuid.UUID `json:"customerId,omitempty"`
	CorporateAccountID *uuid.UUID `json:"corporateAccountId,omitempty"`
	Amount             string     `json:"amount,omitempty" doc:"Amount moved to the other party (or percent)"`
	Percent            string     `json:"percent,omitempty"`
	Reason             string     `json:"reason"`
}

// SplitBilling moves a share of every uninvoiced charge of an open folio to
// another payer; the original folio and its lines are kept (SplitCharges).
func (s *Service) SplitBilling(ctx context.Context, tx pgx.Tx, property, folio uuid.UUID, in BillingSplitInput) (SplitResult, error) {
	if in.CustomerID == nil && in.CorporateAccountID == nil {
		return SplitResult{}, handle.Invalid("corporateAccountId", "required", "choose the company or the customer that pays the share")
	}
	var lines []uuid.UUID
	var total string
	if err := tx.QueryRow(ctx, `SELECT coalesce(array_agg(id ORDER BY posted_at, id), '{}'), coalesce(sum(total), 0)::text FROM billing.folio_lines
		WHERE folio_id = $1 AND property_id = $2 AND voided_at IS NULL AND invoice_id IS NULL`, folio, property).Scan(&lines, &total); err != nil {
		return SplitResult{}, err
	}
	t := dec(total)
	if len(lines) == 0 || !t.IsPositive() {
		return SplitResult{}, errs.Conflict("nothing_to_split", "the folio has no uninvoiced charges")
	}
	pct := strings.TrimSpace(in.Percent)
	if pct == "" {
		a, err := handle.Decimal("amount", in.Amount, decimal.Zero)
		if err != nil || !a.IsPositive() || a.GreaterThan(t) {
			return SplitResult{}, handle.Invalid("amount", "invalid", "between 0 and "+t.String())
		}
		pct = a.Div(t).Mul(decimal.NewFromInt(100)).Round(6).String()
	}
	res, err := s.SplitCharges(ctx, tx, property, SplitInput{LineIDs: lines, Percent: pct, CustomerID: in.CustomerID, CorporateAccountID: in.CorporateAccountID,
		Reason: in.Reason})
	if err != nil {
		return res, err
	}
	summary := fmt.Sprintf("Billing split: %s (%s%%) moved to %s, folio %s", res.Moved, pct, res.TargetFolio.HolderName, res.TargetFolio.Number)
	if err := billingEvent(ctx, tx, property, folio, "billing_split", summary, map[string]any{"targetFolio": res.TargetFolio.ID, "moved": res.Moved,
		"percent": pct}, in.Reason); err != nil {
		return res, err
	}
	return res, billingEvent(ctx, tx, property, res.TargetFolio.ID, "billing_split", "Split from the original folio: "+res.Moved,
		map[string]any{"sourceFolio": folio, "moved": res.Moved, "percent": pct}, in.Reason)
}

// AssignInput assigns an owner to folios.
type AssignInput struct {
	FolioIDs []uuid.UUID `json:"folioIds"`
	OwnerID  *uuid.UUID  `json:"ownerId,omitempty" doc:"null: unassign"`
}

// AssignOwner sets the person responsible for the billing of folios.
func AssignOwner(ctx context.Context, tx pgx.Tx, property uuid.UUID, in AssignInput) (int, error) {
	if len(in.FolioIDs) == 0 {
		return 0, handle.Invalid("folioIds", "required", "choose the folios")
	}
	name := "nobody"
	if in.OwnerID != nil {
		if err := tx.QueryRow(ctx, `SELECT full_name FROM platform.users WHERE id = $1 AND status = 'active'`, *in.OwnerID).Scan(&name); err != nil {
			if dbtx.IsNoRows(err) {
				return 0, handle.Invalid("ownerId", "not_found", "unknown or inactive user")
			}
			return 0, err
		}
	}
	n := 0
	for _, fid := range in.FolioIDs {
		if _, err := ensureRecord(ctx, tx, property, fid); err != nil {
			return n, err
		}
		if _, err := tx.Exec(ctx, `UPDATE billing.billing_records SET owner_id = $2, version = version + 1, updated_by = $3 WHERE folio_id = $1`,
			fid, in.OwnerID, id.Ptr(actor(ctx))); err != nil {
			return n, err
		}
		if err := billingEvent(ctx, tx, property, fid, "owner_assigned", "Owner: "+name, map[string]any{"ownerId": in.OwnerID}, ""); err != nil {
			return n, err
		}
		n++
	}
	return n, nil
}

// BillingOwner is a user who can prepare billing.
type BillingOwner struct {
	ID       uuid.UUID `json:"id" db:"id"`
	FullName string    `json:"fullName" db:"full_name"`
}

// BillingOwners lists the users holding billing.billing.prepare at the property.
func BillingOwners(ctx context.Context, q dbtx.Querier, property uuid.UUID) ([]BillingOwner, error) {
	return handle.List[BillingOwner](q.Query(ctx, `SELECT DISTINCT u.id, u.full_name FROM platform.users u
		JOIN platform.role_assignments ra ON ra.user_id = u.id AND (ra.property_id = $1 OR ra.property_id IS NULL)
		JOIN platform.role_permissions rp ON rp.role_id = ra.role_id AND rp.permission_code = $2
		WHERE u.status = 'active' ORDER BY u.full_name`, property, PermBillingPrepare))
}

// ── routes ────────────────────────────────────────────────────────────────

// BillingNoteInput is a note on the billing of a folio.
type BillingNoteInput struct {
	Body string `json:"body"`
}

// AssignResult counts the folios assigned.
type AssignResult struct {
	Assigned int `json:"assigned"`
}

// RegisterBillingWorkspace adds the routes of Revenue & Billing → Billing.
func (h *HTTP) RegisterBillingWorkspace(reg *route.Registry) {
	db := h.Svc.DB
	add := func(rt route.Route) {
		rt.Module, rt.Tag, rt.Scope = "billing", "Billing Workspace", route.ScopeProperty
		reg.Add(rt)
	}
	folioOf := func(r *http.Request) (uuid.UUID, error) { return handle.ID(r) }
	add(route.Route{Method: http.MethodGet, Path: "/api/v1/billing/billing-queue",
		Summary:    "Billing workspace: folios to bill per business with status (pending billing, ready to invoice, exception, invoiced, cancelled), exceptions and next action",
		Permission: "billing.folio.view", Response: BillingQueue{},
		Query: []route.Param{{Name: "filter[status]", Enum: []string{BillPending, BillReady, BillException, BillInvoiced, BillCancelled}},
			{Name: "filter[group]", Enum: []string{"golf", "resort", "events", "membership", "sport", "fnb", "other"}},
			{Name: "filter[owner]", Description: "Owner user id, or me"}, {Name: "q", Description: "Folio, customer, bill-to, source or invoice number"}},
		Handler: handle.Read(db, func(ctx context.Context, tx pgx.Tx, r *http.Request) (BillingQueue, error) {
			lp := httpx.ParseList(r)
			size := lp.PageSize
			if r.URL.Query().Get("limit") == "" {
				size = 300
			}
			owner := lp.Filters["owner"]
			if owner == "me" {
				owner = actor(ctx).String()
			}
			return Queue(ctx, tx, handle.Property(ctx), lp.Filters["status"], lp.Filters["group"], owner, lp.Q, lp.Offset, size)
		})})
	add(route.Route{Method: http.MethodGet, Path: "/api/v1/billing/billing-owners", Summary: "Users who can prepare billing (owner of a billing record)",
		Permission: "billing.folio.view", Response: BillingOwner{}, List: true,
		Handler: handle.Read(db, func(ctx context.Context, tx pgx.Tx, r *http.Request) (httpx.Page[BillingOwner], error) {
			return handle.Page(BillingOwners(ctx, tx, handle.Property(ctx)))
		})})
	add(route.Route{Method: http.MethodGet, Path: "/api/v1/billing/billing-records/{id}",
		Summary:    "Review / Prepare Billing of a folio: validations, calculation, charges, deposits, adjustments and history",
		Permission: "billing.folio.view", Response: BillingRecordDetail{},
		Handler: handle.Read(db, func(ctx context.Context, tx pgx.Tx, r *http.Request) (BillingRecordDetail, error) {
			fid, err := folioOf(r)
			if err != nil {
				return BillingRecordDetail{}, err
			}
			return GetBillingRecord(ctx, tx, handle.Property(ctx), fid)
		})})
	add(route.Route{Method: http.MethodPut, Path: "/api/v1/billing/billing-records/{id}", Summary: "Save Billing: bill-to, payment term, references, notes and documents",
		Permission: PermBillingPrepare, Request: BillingRecordInput{}, Response: BillingRecordDetail{},
		Handler: handle.Write(db, http.StatusOK, func(ctx context.Context, tx pgx.Tx, r *http.Request, in BillingRecordInput) (BillingRecordDetail, error) {
			fid, err := folioOf(r)
			if err != nil {
				return BillingRecordDetail{}, err
			}
			return SaveBillingRecord(ctx, tx, handle.Property(ctx), fid, in)
		})})
	add(route.Route{Method: http.MethodPost, Path: "/api/v1/billing/billing-records/{id}:mark-ready", Summary: "Mark Ready to Invoice (every validation must pass)",
		Permission: PermBillingPrepare, Request: handle.Empty{}, Response: BillingRecordDetail{}, Status: http.StatusOK,
		Handler: handle.Write(db, http.StatusOK, func(ctx context.Context, tx pgx.Tx, r *http.Request, _ handle.Empty) (BillingRecordDetail, error) {
			fid, err := folioOf(r)
			if err != nil {
				return BillingRecordDetail{}, err
			}
			return MarkReady(ctx, tx, handle.Property(ctx), fid)
		})})
	add(route.Route{Method: http.MethodPost, Path: "/api/v1/billing/billing-records/{id}:approve",
		Summary:    "Approve high-value billing and its adjustments (Finance Manager; General Manager / Director above the executive threshold)",
		Permission: PermBillingApprove, Request: ReasonRequest{}, Response: BillingRecordDetail{}, Status: http.StatusOK,
		Handler: handle.Write(db, http.StatusOK, func(ctx context.Context, tx pgx.Tx, r *http.Request, in ReasonRequest) (BillingRecordDetail, error) {
			fid, err := folioOf(r)
			if err != nil {
				return BillingRecordDetail{}, err
			}
			return ApproveBilling(ctx, tx, handle.Property(ctx), fid, in.Reason)
		})})
	add(route.Route{Method: http.MethodPost, Path: "/api/v1/billing/billing-records/{id}/exceptions/{code}:resolve",
		Summary:    "Resolve an exception: acknowledge (accountant) or override (Finance Manager) with a reason",
		Permission: PermBillingPrepare, Request: ReasonRequest{}, Response: BillingRecordDetail{}, Status: http.StatusOK,
		Handler: handle.Write(db, http.StatusOK, func(ctx context.Context, tx pgx.Tx, r *http.Request, in ReasonRequest) (BillingRecordDetail, error) {
			fid, err := folioOf(r)
			if err != nil {
				return BillingRecordDetail{}, err
			}
			return ResolveException(ctx, tx, handle.Property(ctx), fid, chi.URLParam(r, "code"), in.Reason)
		})})
	add(route.Route{Method: http.MethodPost, Path: "/api/v1/billing/billing-records/{id}/notes", Summary: "Add a note to the billing of a folio",
		Permission: PermBillingPrepare, Request: BillingNoteInput{}, Response: BillingRecordDetail{}, Status: http.StatusOK,
		Handler: handle.Write(db, http.StatusOK, func(ctx context.Context, tx pgx.Tx, r *http.Request, in BillingNoteInput) (BillingRecordDetail, error) {
			fid, err := folioOf(r)
			if err != nil {
				return BillingRecordDetail{}, err
			}
			if err := handle.Required("body", strings.TrimSpace(in.Body)); err != nil {
				return BillingRecordDetail{}, err
			}
			p := handle.Property(ctx)
			if _, err := ensureRecord(ctx, tx, p, fid); err != nil {
				return BillingRecordDetail{}, err
			}
			if err := billingEvent(ctx, tx, p, fid, "note", strings.TrimSpace(in.Body), nil, ""); err != nil {
				return BillingRecordDetail{}, err
			}
			return GetBillingRecord(ctx, tx, p, fid)
		})})
	add(route.Route{Method: http.MethodPost, Path: "/api/v1/billing/billing-records/{id}/adjustments",
		Summary:    "Adjust a charge before invoicing (quantity, price, discount, service charge, tax, revenue allocation) with a reason",
		Permission: PermBillingPrepare, Request: BillingAdjustmentInput{}, Response: BillingRecordDetail{}, Status: http.StatusOK,
		Handler: handle.Write(db, http.StatusOK, func(ctx context.Context, tx pgx.Tx, r *http.Request, in BillingAdjustmentInput) (BillingRecordDetail, error) {
			fid, err := folioOf(r)
			if err != nil {
				return BillingRecordDetail{}, err
			}
			return h.Svc.AdjustBilling(ctx, tx, handle.Property(ctx), fid, in)
		})})
	add(route.Route{Method: http.MethodPost, Path: "/api/v1/billing/billing-records/{id}:split",
		Summary:    "Split Billing: move a share of the folio's uninvoiced charges to another company or customer (open folios)",
		Permission: PermBillingPrepare, Request: BillingSplitInput{}, Response: SplitResult{}, Status: http.StatusOK,
		Handler: handle.Write(db, http.StatusOK, func(ctx context.Context, tx pgx.Tx, r *http.Request, in BillingSplitInput) (SplitResult, error) {
			fid, err := folioOf(r)
			if err != nil {
				return SplitResult{}, err
			}
			return h.Svc.SplitBilling(ctx, tx, handle.Property(ctx), fid, in)
		})})
	add(route.Route{Method: http.MethodPost, Path: "/api/v1/billing/billing-records:generate",
		Summary:    "Generate Invoices: one issued invoice per folio without a blocking exception (the others are skipped with the reason)",
		Permission: "billing.invoice.create", Request: BillingGenerateInput{}, Response: BillingGenerateResults{}, Status: http.StatusOK,
		Handler: handle.Write(db, http.StatusOK, func(ctx context.Context, tx pgx.Tx, r *http.Request, in BillingGenerateInput) (BillingGenerateResults, error) {
			return h.GenerateInvoices(ctx, tx, handle.Property(ctx), in)
		})})
	add(route.Route{Method: http.MethodPost, Path: "/api/v1/billing/billing-records:consolidate",
		Summary:    "Consolidate: one invoice for several folios of the same payer, each line linked to its folio (Finance Manager)",
		Permission: PermBillingApprove, Request: ConsolidateInput{}, Response: BillingGenerateResult{}, Status: http.StatusOK,
		Handler: handle.Write(db, http.StatusOK, func(ctx context.Context, tx pgx.Tx, r *http.Request, in ConsolidateInput) (BillingGenerateResult, error) {
			return h.ConsolidateBilling(ctx, tx, handle.Property(ctx), in)
		})})
	add(route.Route{Method: http.MethodPost, Path: "/api/v1/billing/billing-records:assign", Summary: "Assign Owner of the billing of folios",
		Permission: PermBillingPrepare, Request: AssignInput{}, Response: AssignResult{}, Status: http.StatusOK,
		Handler: handle.Write(db, http.StatusOK, func(ctx context.Context, tx pgx.Tx, r *http.Request, in AssignInput) (AssignResult, error) {
			n, err := AssignOwner(ctx, tx, handle.Property(ctx), in)
			return AssignResult{Assigned: n}, err
		})})
}
