package e2e

// EP-18 Rhapsody migration: stage → validate (row errors) → load
// (idempotent) → reconcile against the Rhapsody control totals.

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"oneclub/internal/app/rhapsody"
)

func TestP1RhapsodyMigration(t *testing.T) {
	dir := t.TempDir()
	day := clubDay(inst, 9, isWeekday)
	// slot generated by the WEEKDAY morning template (05:30 + 8 min steps)
	files := map[string]string{
		"customers.csv": "legacy_id,name,gender,birth_date,email,phone,handicap_index\n" +
			"C9001,Gunawan Rhapsody,M,12/05/1970,gunawan@example.test,0811900001,10.4\n" +
			"C9002,Herlina Rhapsody,F,1975-08-01,herlina@example.test,0811900002,\n" +
			"C9003,Iwan Rhapsody,M,2008-01-20,,0811900003,\n" +
			"C9004,Joni BadDate,M,31/31/1999,,0811900004,\n",
		"corporate_accounts.csv": "legacy_id,name,npwp\nK001,PT Rhapsody Corp,01.111.222.3-444.000\n",
		"corporate_nominees.csv": "corporate_legacy_id,customer_legacy_id,title\nK001,C9001,Director\n",
		"members.csv": "member_no,customer_legacy_id,type_code,starts_on,ends_on,status,card_number,principal_member_no,relationship\n" +
			"R1001,C9001,IND,01/01/2026,31/12/2026,A,RH-CARD-1001,,\n" +
			"R1002,C9002,FAM,2026-02-01,2027-01-31,A,RH-CARD-1002,,\n" +
			"R1003,C9003,FAM,2026-02-01,2027-01-31,A,,R1002,child\n" +
			"R1004,C9004,GOLD,2026-01-01,2026-12-31,A,,,\n",
		"opening_balances.csv": "member_no,balance,as_of\nR1001,\"1,250,000\",2026-09-30\nR1002,0,2026-09-30\n",
		"caddies.csv":          "code,name,gender\nRC01,Rhapsody Caddy One,F\nRC02,Rhapsody Caddy Two,F\n",
		"golf_carts.csv":       "code,name,cart_type\nRB01,Rhapsody Buggy 1,electric\n",
		"lockers.csv":          "code,name,area,zone\nRL01,Rhapsody Locker 1,M,A\nRL02,Rhapsody Locker 2,X,A\n",
		"future_bookings.csv": "legacy_ref,course_code,play_date,tee_time,start_tee,member_no,contact_name,contact_phone,players,player_names,paid_amount\n" +
			"RB-77001,MGC," + day + ",07:06,1,R1001,Gunawan Rhapsody,0811900001,2,;Tamu Gunawan,\n" +
			"RB-77002,MGC," + day + ",07:14,1,,Walk In Rhapsody,0811900009,2,Walk In Rhapsody;Teman,1990000\n",
		"control_totals.csv": "metric,value\ncustomers,3\ncorporate_accounts,1\nmembers,3\nactive_members:IND,1\nactive_members:FAM,2\n" +
			"member_account_balance,1250000\nfuture_bookings,2\ncaddies,2\ngolf_carts,1\nlockers,1\n",
	}
	for name, body := range files {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(body), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	ctx := context.Background()
	counts, err := rhapsody.Stage(ctx, inst.DB, dir)
	if err != nil {
		t.Fatal(err)
	}
	if counts["members"] != 4 || counts["future_bookings"] != 2 {
		t.Fatalf("staged: %v", counts)
	}
	d := &rhapsody.Deps{DB: inst.DB, Engine: inst.App.Engine, Golf: inst.App.Golf, Billing: inst.App.Billing, Location: inst.App.Instance.Location}
	issues, err := d.Validate(ctx, inst.Main)
	if err != nil {
		t.Fatal(err)
	}
	want := map[string]bool{"customers:birth_date": false, "members:type_code": false, "lockers:area": false}
	for _, i := range issues {
		k := i.Entity + ":" + i.Field
		if _, ok := want[k]; ok {
			want[k] = true
		}
	}
	for k, found := range want {
		if !found {
			t.Fatalf("validation should report %s: %+v", k, issues)
		}
	}
	for run := 0; run < 2; run++ { // the second run proves idempotency (dry run ×2)
		reps, err := d.Load(ctx, inst.Main)
		if err != nil {
			t.Fatal(err)
		}
		for _, r := range reps {
			if r.Failed > 0 && r.Entity != "members" {
				t.Fatalf("load %s: %+v", r.Entity, r)
			}
		}
	}
	totals, err := rhapsody.ReadTotals(filepath.Join(dir, "control_totals.csv"))
	if err != nil {
		t.Fatal(err)
	}
	checks, err := d.Reconcile(ctx, inst.Main, totals)
	if err != nil {
		t.Fatal(err)
	}
	var bad []string
	for _, c := range checks {
		if !c.Match {
			bad = append(bad, c.Metric+" rhapsody="+c.Rhapsody+" oneclub="+c.OneClub)
		}
	}
	if len(bad) > 0 {
		t.Fatalf("reconciliation mismatches:\n%s", strings.Join(bad, "\n"))
	}
	// the migrated member can be found by the Rhapsody card number at check-in
	gm := login(t, inst, "golf.manager@demo.oneclub.id", demoPassword)
	cands := gm.Must(200, "GET", "/api/v1/golf/check-ins:lookup?method=member_card&value=RH-CARD-1001&date="+day, nil).Items()
	if len(cands) != 1 {
		t.Fatalf("migrated booking by legacy card: %v", cands)
	}
}
